FW利用者がSceneTransitionを使えるようにする
extreal-dev/Extreal.Guide pull request #12
Opened 2022-10-22 17:09 UTC by kiyohome

https://github.com/extreal-dev/Extreal.Core.SceneTransition/issues/2

# Describe Your Changes (なんの変更を加えましたか?)

- SceneTransitionの機能ページを書きました。
- その他、気になったとこを修正しました
  - グランドデザインの「場面」→「シーン」に変更。SceneTransition書いてて気になりました。
  - ログのコメントでNOTE→INFOに変更。NOTEはFW開発者向けのメモに感じるので。TODOとかであればよいのですが。

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

2022-10-24 03:02 UTC, sus-taguchi-t requested changes

2022-10-24 03:02 UTC, sus-taguchi-t commented on docs/core/scene-transition.md
> +    LOGGER.logInfo(sceneName);
`logInfo()` -> `LogInfo()`

2022-10-24 04:55 UTC, kiyohome commented on docs/core/scene-transition.md
> +### 遷移履歴に従って遷移元に戻る
Resetの使用方法を追記しましょう。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3#pullrequestreview-1152188847

2022-10-24 08:34 UTC, kiyohome commented on docs/core/scene-transition.md
> +
忘れてました！
追記しました。
https://github.com/extreal-dev/Extreal.Guide/pull/12/commits/c677f2adf565a0116fb0d83c8edfaeb36b458a68

2022-10-24 08:36 UTC, kiyohome commented on docs/core/scene-transition.md
> +// Enum for the UUnity scene name
すみません、修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/12/commits/7a1ba0092f1e66c8757d6d3632679b1d4f1af0f5

2022-10-24 08:38 UTC, kiyohome commented on docs/core/scene-transition.md
> +    }
ありがとうございます！
2つ目で追記しました！
https://github.com/extreal-dev/Extreal.Guide/pull/12/commits/8e0878ff4b812fdb0f80bbe6e36b1b11d08933c7

2022-10-24 08:40 UTC, kiyohome commented on docs/core/scene-transition.md
> +    LOGGER.logInfo(sceneName);
すみません、中々Javaの癖が抜けないです。。。
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/12/commits/42cac400a393fdf1e12bd6cb7024fa7e6652e125

2022-10-24 09:07 UTC, kiyohome commented on docs/core/scene-transition.md
> +### 遷移履歴に従って遷移元に戻る
Resetの説明を追記しました！
https://github.com/extreal-dev/Extreal.Guide/pull/12/commits/2c521717c22656c91e00383e07123a5880b8dbe9

2022-10-25 03:21 UTC, sus-taguchi-t commented on docs/core/scene-transition.md
> +
確認しました。

2022-10-25 03:21 UTC, sus-taguchi-t commented on docs/core/scene-transition.md
> +// Enum for the UUnity scene name
確認しました。

2022-10-25 03:22 UTC, sus-taguchi-t commented on docs/core/scene-transition.md
> +    }
確認しました。

2022-10-25 03:23 UTC, sus-taguchi-t commented on docs/core/scene-transition.md
> +    LOGGER.logInfo(sceneName);
確認しました。

2022-10-25 03:24 UTC, sus-taguchi-t approved these changes

2022-10-25 03:25 UTC, merged