FW利用者がResourceProviderを使えるようにする
extreal-dev/Extreal.Guide pull request #13
Opened 2022-10-23 08:56 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- ResourceProviderの機能ページを追加しました

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

2022-10-24 04:44 UTC, sus-taguchi-t requested changes

2022-10-24 04:44 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    }
`+LogicalPath ResourceName` も公開します。

2022-10-24 04:44 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +
`Extreal.Core.Logging` および `UniTask` に依存します。

2022-10-24 04:44 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    menuName = "Configuration/" + nameof(ResourceConfig),
`Configuration` -> `Config`

2022-10-24 04:44 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    public List<Resource<ResourceName>> _Resources => _resources;
`_Resources` -> `Resources`

2022-10-24 04:44 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    }
```cs
builder.ResisterInstance<IResourceConfig>(_resourceConfig);
```
ないしは
```cs
builder.ResisterInstance(_resourceConfig).AsImplementedInterfaces();
```
も必要です。

2022-10-24 04:44 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +```
フォーマットが異なります。
```cs
public class AppResourceProvider : IResourceProvider
{
    public AppResouceProvider(IResourceConfig config)
    {
        // do something
    }
}
```

2022-10-24 04:44 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    }
```cs
builder.ResisterInstance<IResourceConfig>(_resourceConfig);
```
ないしは
```cs
builder.ResisterInstance(_resourceConfig).AsImplementedInterfaces();
```
も必要です。

2022-10-24 05:34 UTC, sus-taguchi-t requested changes

2022-10-24 05:34 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +        +UnityResourcesResourceProvider(configuraiton)
`configuration` -> `config`

2022-10-24 09:16 UTC, kiyohome commented on docs/core/resource-provider.md
> +    }
LogicalPathでなく名前ですね。任意の名前を付けるイメージです。
追加しました！
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/09b84c9501fca9ab7b54cd7b4d4628c037248250

2022-10-24 09:18 UTC, kiyohome commented on docs/core/resource-provider.md
> +
追加しました！
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/26ad72701bd1c96c9aca9a18c970fb1b69d822c9

2022-10-24 09:19 UTC, kiyohome commented on docs/core/resource-provider.md
> +    menuName = "Configuration/" + nameof(ResourceConfig),
残ってましたね、すみません。
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/f043230f21c9739e194472959a8f374a3dc1cf50

2022-10-24 09:20 UTC, kiyohome commented on docs/core/resource-provider.md
> +    public List<Resource<ResourceName>> _Resources => _resources;
よく気づきましたね！すごい！
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/631a25408a74690030072ec1fc102e54608e8228

2022-10-24 09:21 UTC, kiyohome commented on docs/core/resource-provider.md
> +    }
ありがとうございます！
追加しました。
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/29a69b9af88ebb246afc4c8d42af4acc682e4d29

2022-10-24 09:23 UTC, kiyohome commented on docs/core/resource-provider.md
> +```
すみません、ホントに中々抜けない。。。
修正しましたー
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/d25801afd2fb035368bf9d0b3687c5a21a271866

2022-10-24 09:26 UTC, kiyohome commented on docs/core/resource-provider.md
> +    }
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/5a58d9f278f3833cbdeedcf52046d947e149a531

2022-10-24 09:27 UTC, kiyohome commented on docs/core/resource-provider.md
> +        +UnityResourcesResourceProvider(configuraiton)
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/13/commits/632ba279483e19c5b5d5de59567f3855e08907c5

2022-10-25 03:27 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    }
確認しました。

2022-10-25 03:27 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +
確認しました。

2022-10-25 03:28 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    menuName = "Configuration/" + nameof(ResourceConfig),
確認しました。

2022-10-25 03:29 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    public List<Resource<ResourceName>> _Resources => _resources;
頑張りました！
確認しました。

2022-10-25 03:30 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    }
確認しました。

2022-10-25 03:30 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +```
癖って難しいですよね。。
確認しました。

2022-10-25 03:30 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +    }
確認しました。

2022-10-25 03:31 UTC, sus-taguchi-t commented on docs/core/resource-provider.md
> +        +UnityResourcesResourceProvider(configuraiton)
確認しました。

2022-10-25 03:31 UTC, sus-taguchi-t approved these changes

2022-10-25 03:31 UTC, merged