サンプルアプリの内容を書く
extreal-dev/Extreal.Guide pull request #17
Opened 2022-10-27 07:50 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- サンプルアプリの内容を書き中です。

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

2022-10-27 08:24 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - ルームに入室できる
ロビーの時点でもうマルチプレイができるようにして大丈夫でしょうか？
SimpleMultiplayerApp ではロビーではまだマルチプレイができない仕様でした。

2022-10-27 08:24 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +      - 21人目からは非表示、20人のマルチプレイは見れる
21 人目に入った人は 20 人目までの誰かが抜けたら表示されるようになるのでしょうか？

2022-10-28 01:37 UTC, kiyohome commented on docs/sample-app/requirements.md
> +  - ルームに入室できる
ロビーは選択ページだけにしましょう。

2022-10-28 01:53 UTC, kiyohome commented on docs/sample-app/requirements.md
> +      - 21人目からは非表示、20人のマルチプレイは見れる
できればそうしたいです。

2022-10-31 00:44 UTC, kiyohome commented on docs/sample-app/requirements.md
> +  - ルームに入室できる
ルーム選択ページに変更しました。
https://github.com/extreal-dev/Extreal.Guide/pull/17/commits/d3f75f562d1179ba60d49392ae4ede1db31ff31f

2022-10-31 01:23 UTC, kiyohome commented on docs/sample-app/requirements.md
> +      - 21人目からは非表示、20人のマルチプレイは見れる
マルチプレイの制約を見直しました。
https://github.com/extreal-dev/Extreal.Guide/pull/17/commits/b0d9bb9bb2fcddd512894a8325b026221b4fc14a

2022-11-14 02:26 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +
アセット管理にAddressablesを使ってることを書くのを忘れてました。

2022-11-14 02:44 UTC, sus-taguchi-t requested changes

2022-11-14 02:44 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +        builder.RegisterComponent(avatarSelectionScreenView);
`RegisterComponent()` の存在を失念していたのですが、`StageNavigation` や `ResourceProvider` のガイドの Settings でも `RegisterInstance()` ではなくこれを使用させるように変更した方が良いですかね？

2022-11-14 04:19 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +```
共通処理が出てきた場合はこの中に入れるつもりでした。
やるとするとCommon＞Prefabsとかになるんですが現状はCommonだけでいいと思っています。

2022-11-14 04:30 UTC, kiyohome commented on docs/sample-app/requirements.md
> +  - ルームに入室できる
ルーム選択ページを無くしました。

2022-11-14 04:30 UTC, kiyohome commented on docs/sample-app/requirements.md
> +      - 21人目からは非表示、20人のマルチプレイは見れる
さらに見直しました。

2022-11-14 04:31 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +
追記しました！
https://github.com/extreal-dev/Extreal.Guide/pull/17/commits/aaf39578cf319f779ad568ecf37f5a46cf0336a3

2022-11-14 04:32 UTC, kiyohome commented on docs/sample-app/requirements.md
> +      - 120人目以降はステージにアクセスできない
あー確かに！
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/17/commits/19095393d2c670b59ccc257da65903a200428286

2022-11-14 04:49 UTC, kiyohome commented on docs/sample-app/test-planning.md
> +## 共通
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/17/commits/bc4f8bbdb2fe6cc9415c04981d5c3a577c178267

2022-11-14 04:58 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +## ディレクトリ構成
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/17/commits/173dfef9725561900ed7c1ac504254416de80131

2022-11-14 05:05 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +        builder.RegisterComponent(avatarSelectionScreenView);
ResourceProviderは削除するのでいいです。
StageNavigationのガイドとサンプルアプリのソースを修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/17/commits/9c8e9b929f6f329aae7ce489aaf3fcefc903dcc2
https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/1/commits/fd872eabf4f8315c2e657daa8a1fcd0e32a5af98

2022-11-14 05:08 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - ルームに入室できる
確認しました！

2022-11-14 05:08 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +      - 21人目からは非表示、20人のマルチプレイは見れる
確認しました！

2022-11-14 05:10 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +
確認しました！

2022-11-14 05:10 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +      - 120人目以降はステージにアクセスできない
確認しました！

2022-11-14 05:12 UTC, sus-taguchi-t commented on docs/sample-app/test-planning.md
> +## 共通
確認しました！

2022-11-14 05:12 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +## ディレクトリ構成
確認しました！

2022-11-14 05:15 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +        builder.RegisterComponent(avatarSelectionScreenView);
確認しました！

2022-11-14 05:17 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +```
分かりました。
ありがとうございます。
ではこのままでいきましょう。

2022-11-14 05:18 UTC, sus-taguchi-t approved these changes

2022-11-14 05:18 UTC, merged