11/2FB対応
extreal-dev/Extreal.Guide pull request #20
Opened 2022-11-06 01:35 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

2022-11-07 01:20 UTC, sus-taguchi-t requested changes

2022-11-07 01:20 UTC, sus-taguchi-t commented on docs/intro.md
>  ![Multiple scenes](/img/multi-scenes.png)
画像内の typo.
`TitleScree` -> `TitleScreen`

2022-11-08 00:24 UTC, kiyohome commented on docs/core/stage-navigation.md
> +    LOGGER.LogInfo(stage);
すみません、修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/20/commits/424dadf321cc9a831815725e8f40e1e51091c5e8

2022-11-08 00:25 UTC, kiyohome commented on docs/intro.md
>  ![Multiple scenes](/img/multi-scenes.png)
すみません、修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/20/commits/df5bb3b286d89b8b1b74826d093ff5735ca1d435

2022-11-08 00:42 UTC, sus-taguchi-t commented on docs/core/stage-navigation.md
> +    LOGGER.LogInfo(stage);
確認しました！

2022-11-08 00:43 UTC, sus-taguchi-t approved these changes

2022-11-08 00:43 UTC, merged