11/24FB対応
extreal-dev/Extreal.Guide pull request #23
Opened 2022-11-25 13:18 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- [ ] Core＞ResourceProvider：削除

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

- [ ] 気になるとこを中心に確認をお願いします。

2022-11-28 09:25 UTC, sus-taguchi-t requested changes

2022-11-28 09:25 UTC, sus-taguchi-t commented on docs/learning/core.md
>      }
333, 335 行目
`IStageNavigator` -> `StageNavigator`

2022-11-28 09:25 UTC, sus-taguchi-t commented on docs/learning/core.md
> +            builder.Register<StageNavigator<StageName, SceneName>>(Lifetime.Singleton).AsImplementedInterfaces();
`.AsImplementedInterfaces()` は不要。

2022-11-28 09:25 UTC, sus-taguchi-t commented on docs/learning/core.md
> +    }
452, 456 行目
`IStageNavigator` -> `StageNavigator`

2022-11-28 09:28 UTC, sus-taguchi-t commented on docs/core/logging.md
>  ```
改めてこのままで良いと思いました。
このスニペットの直前に
>フレームワークやアプリケーションのどの機能よりも先にログ出力を初期化して利用できる状態にする必要があります
<という文言がしっかり書かれていて、これを読めば意図は伝わると思うためです。

2022-11-28 12:19 UTC, kiyohome commented on docs/core/logging.md
>  ```
('◇')ゞ

2022-11-28 12:33 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +  - Code Crackerを適用するにはチェック対象のADにCode Crackerを含める必要があります。
追加しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/b305aa2a76e697891be13abbd4c3e3344ce2977e

2022-11-28 12:40 UTC, kiyohome commented on docs/learning/core.md
> +            IStageNavigator<StageName> stageNavigator = new StageNavigator<StageName, SceneName>(stageConfig);
修正しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/7919338f90b4897b18cc4b01ce2d5a41b6151b33

2022-11-28 12:41 UTC, kiyohome commented on docs/learning/core.md
>      }
修正しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/7919338f90b4897b18cc4b01ce2d5a41b6151b33

2022-11-28 12:42 UTC, kiyohome commented on docs/learning/core.md
> +    }
修正しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/7919338f90b4897b18cc4b01ce2d5a41b6151b33

2022-11-28 12:45 UTC, kiyohome commented on docs/learning/core.md
> +            builder.Register<StageNavigator<StageName, SceneName>>(Lifetime.Singleton).AsImplementedInterfaces();
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/8ed9ade0533fac7208f58526793b7b7455202da7

2022-11-28 12:48 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +    }
修正しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/1e3ed54c78758ee123b9a38e369a4fe85225b8ff

2022-11-28 12:53 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +## Object
修正しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/dc745f4c933d6f7d501d66faaaf1c0f60870741d

2022-11-28 12:53 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +## Asset
修正しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/dc745f4c933d6f7d501d66faaaf1c0f60870741d

2022-11-28 13:00 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +意図しない変更差分が出ないようにスクリプトや設定ファイルのエンコーディングは`UTF-8`に統一してください。
追記しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/411492f16a745044edf3f15860c425c28473aeba

2022-11-28 13:13 UTC, kiyohome commented on docs/learning/core.md
>  ```
修正しました
https://github.com/extreal-dev/Extreal.Guide/pull/23/commits/e072fb12726435d0a778a249685dc78cad50c7f8

2022-11-29 00:14 UTC, sus-taguchi-t commented on docs/learning/core.md
> +            IStageNavigator<StageName> stageNavigator = new StageNavigator<StageName, SceneName>(stageConfig);
確認しました！

2022-11-29 00:16 UTC, sus-taguchi-t commented on docs/learning/core.md
>  ```
確認しました！

2022-11-29 00:17 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +  - Code Crackerを適用するにはチェック対象のADにCode Crackerを含める必要があります。
確認しました！

2022-11-29 00:17 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +意図しない変更差分が出ないようにスクリプトや設定ファイルのエンコーディングは`UTF-8`に統一してください。
確認しました！

2022-11-29 00:18 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +## Object
確認しました！

2022-11-29 00:18 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +## Asset
確認しました！

2022-11-29 00:18 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
>  ## Scene
確認しました！

2022-11-29 00:19 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +    }
確認しました！

2022-11-29 00:21 UTC, sus-taguchi-t commented on docs/learning/core.md
>      }
確認しました！

2022-11-29 00:22 UTC, sus-taguchi-t commented on docs/learning/core.md
> +            builder.Register<StageNavigator<StageName, SceneName>>(Lifetime.Singleton).AsImplementedInterfaces();
確認しました！

2022-11-29 00:23 UTC, sus-taguchi-t commented on docs/learning/core.md
> +    }
確認しました！

2022-11-29 00:24 UTC, sus-taguchi-t approved these changes

2022-11-29 00:25 UTC, merged