FW利用者がNGOラッパーを学習できるようにする
extreal-dev/Extreal.Guide pull request #28
Opened 2022-12-06 16:22 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- NGOラッパーの学習ページを追加しました。

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

- [ ] 実際に試して最後まで出来ましたか？
- [ ] 伝えたいことは他にありますか？

2022-12-07 08:08 UTC, sus-taguchi-t requested changes

2022-12-07 08:34 UTC, kiyohome commented on docs/learning/multiplay.ngo.md
> +  - 2021.3.11f1
すみません、修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/28/commits/0cdf12f481acd83737872dc01b0979ec9cbf2e04

2022-12-07 08:54 UTC, kiyohome commented on docs/learning/multiplay.ngo.md
> +        private CompositeDisposable disposables = new CompositeDisposable();
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/28/commits/9486ff0301c047cafe71e733b4463a6ec1638e97

2022-12-07 08:54 UTC, kiyohome commented on docs/learning/multiplay.ngo.md
> +        private CompositeDisposable disposables = new CompositeDisposable();
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/28/commits/9486ff0301c047cafe71e733b4463a6ec1638e97

2022-12-07 08:58 UTC, kiyohome commented on docs/learning/multiplay.ngo.md
> +- StageConfigのインスペクタでVirtualStageにMultiplayControlシーンを追加します。
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/28/commits/dbc31e33bd7e068f672c4572bf8b0902b50fc8a8

2022-12-07 08:59 UTC, kiyohome commented on docs/learning/multiplay.ngo.md
> +今回はアプリケーションからメッセージの内容を何も送ってませんが、メッセージの内容でアバター名を送りユーザーごとに選択したアバターをプレイヤーとしてスポーンするといったこともできます。
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/28/commits/6320a5f411dc773a4dbe982c37d4b9f9aae810c4

2022-12-07 10:18 UTC, kiyohome commented on docs/learning/multiplay.ngo.md
> +ParrelSyncで2つのUnityエディタを開いてプレイしている様子です。
すみません、修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/28/commits/289079e8bf7db12ab0f0fc444d005986d462b385

2022-12-07 10:19 UTC, kiyohome commented on docs/learning/multiplay.ngo.md
> +タイトル画面のGoボタンを押してバーチャル空間に移動できれば成功です。
No camerasにならないように学習用プロジェクトを修正しました！
https://github.com/extreal-dev/Extreal.Learning/commit/59e0d077bb6608866ec4090806e03557f303db4e

2022-12-08 02:07 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +  - 2021.3.11f1
確認しました！

2022-12-08 02:12 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +        private CompositeDisposable disposables = new CompositeDisposable();
確認しました！

2022-12-08 02:13 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +        private CompositeDisposable disposables = new CompositeDisposable();
確認しました！

2022-12-08 02:16 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +- StageConfigのインスペクタでVirtualStageにMultiplayControlシーンを追加します。
すみません、コメントの選択範囲が見切れていたようです。
ここの 1 つ上の「SceneNameにMultiplayControlシーンを追加します。」という文に関しても同様に「MultiplayControl を追加」の方が分かりやすいと思います。

2022-12-08 02:17 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +今回はアプリケーションからメッセージの内容を何も送ってませんが、メッセージの内容でアバター名を送りユーザーごとに選択したアバターをプレイヤーとしてスポーンするといったこともできます。
確認しました！

2022-12-08 02:17 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +        private CompositeDisposable disposables = new CompositeDisposable();
確認しました！

2022-12-08 02:24 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +タイトル画面のGoボタンを押してバーチャル空間に移動できれば成功です。
確認しました！

2022-12-08 02:50 UTC, sus-taguchi-t commented on docs/learning/multiplay.ngo.md
> +- StageConfigのインスペクタでVirtualStageにMultiplayControlシーンを追加します。
確認しました！

2022-12-08 02:51 UTC, sus-taguchi-t approved these changes

2022-12-08 02:51 UTC, merged