Learning.Vivoxを書いた
extreal-dev/Extreal.Guide pull request #29
Opened 2022-12-12 00:45 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- Vivoxラッパーの学習ページを追加しました。

# What operation was verified? (なんの動作を確認しましたか?)

- [x] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

- [ ] 実際に試して最後まで出来ましたか？
- [ ] 伝えたいことは他にありますか？

2022-12-12 03:29 UTC, sus-taguchi-t requested changes

2022-12-12 03:29 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            }).AddTo(sceneDisposables);
`stageDisposables.Dispose()` を `stageDisposables.Clear()` にすれば `OnStageTransitioned` の度に `stageDisposables` インスタンス化する必要がなくなります。
またこれを採用する場合は `Dispose` メソッドの中で `stageDisposables.Dispose()` を呼ぶ必要があります。

2022-12-12 03:29 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            StageName stageName, CompositeDisposable stageDisposables);
`sceneDisposables` および `stageDisposables` を `protected` にすれば `Initialize` メソッドおよび `OnStageEntered` メソッドに `CompositeDisposable` を投げる必要はなくなります。

2022-12-12 03:29 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +        }
`Dispose` メソッドはオーバーライドできた方が良いと思うので `virtual` 修飾子を付けた方が良いと思います。

2022-12-12 03:29 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            VivoxClient.Connect(new VivoxChannelConfig(ChannelName, ChatType.TextOnly, transmissionSwitch: false));
`VivoxClient.Connect(new VivoxChannelConfig(ChannelName, ChatType.TextOnly, transmissionSwitch: false))`
-> `Connect()`

2022-12-12 03:39 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +                .Subscribe(channelId => { this.channelId = channelId; })
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/29/commits/e1807bbb219ca8e7ffa196a500f3580ced431139

2022-12-12 03:42 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +            await UniTask.WaitUntil(IsLoggedIn);
ハンズオンなのでログイン出来る前提でもいいんですが、
アプリだとどうしておくのがいい感じですか？
Vivoxの状態を見て遷移させる？

2022-12-12 03:48 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +        }
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/29/commits/f7c6e18d07aab107b5722a82d2087b3122f2217d

2022-12-12 03:55 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +            stageDisposables.Dispose();
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/29/commits/6f52d2040959aa108d57d116169779dbef14e1ee

2022-12-12 03:57 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +            this.VivoxClient.OnChannelSessionAdded
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/29/commits/e0534005e6a4cedfa81b0c7ca03d58756f948383

2022-12-12 04:01 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +            }).AddTo(sceneDisposables);
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/29/commits/bfe5b0bec701c63d38c90b3a01045e8b1ec5c618

2022-12-12 04:04 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +            StageName stageName, CompositeDisposable stageDisposables);
メソッド引数とprotectedフィールドに分散するのを避けたくメソッド引数に寄せてます。
ModelのBaseクラスは仕方なくprotectedを使ってますが、できるだけメソッド引数にして明示したいと思っています。

2022-12-12 04:06 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +        }
したくなったら付ければいいと思い付けませんでした。
理由があればアプリ内のBaseクラスなのでいつでも変更していいと思います。

2022-12-12 05:24 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +            await UniTask.WaitUntil(IsLoggedIn);
LoggedInだけでなくRecoveryStateで失敗したかも見るように修正する

2022-12-12 07:53 UTC, kiyohome commented on docs/learning/chat.vivox.md
> +            await UniTask.WaitUntil(IsLoggedIn);
一旦、現状のままとさせてください。

2022-12-13 00:26 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +                .Subscribe(channelId => { this.channelId = channelId; })
確認しました！

2022-12-13 00:28 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +        }
確認しました！

2022-12-13 00:28 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            await UniTask.WaitUntil(IsLoggedIn);
分かりました。

2022-12-13 00:29 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            stageDisposables.Dispose();
確認しました！

2022-12-13 00:29 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            this.VivoxClient.OnChannelSessionAdded
確認しました！

2022-12-13 00:30 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            }).AddTo(sceneDisposables);
確認しました！

2022-12-13 00:31 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            StageName stageName, CompositeDisposable stageDisposables);
分かりました。

2022-12-13 00:31 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +        }
分かりました。

2022-12-13 00:32 UTC, sus-taguchi-t commented on docs/learning/chat.vivox.md
> +            VivoxClient.Connect(new VivoxChannelConfig(ChannelName, ChatType.TextOnly, transmissionSwitch: false));
確認しました！

2022-12-13 00:58 UTC, sus-taguchi-t approved these changes

2022-12-13 00:58 UTC, merged