FW利用者が海外の人でも使えるようにガイドを英語にする
extreal-dev/Extreal.Guide pull request #33
Opened 2022-12-23 05:02 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

- [ ]  英語版の準備
- [ ]  LP、Introduction、Release
- [ ]  Core.Logging
- [ ]  Core.StageNavigation
- [ ]  Integration.Chat.Vivox
- [ ]  Integration.Multiplay.NGO
- [ ]  SampleApp
- [ ]  Learning.Introduction、Learning.Core
- [ ]  Learning.Chat.Vivox
- [ ]  Learning.Multiplay.NGO

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました！

# Message to reviewers (レビュアーへのメッセージ)

2023-01-05 03:18 UTC, sus-taguchi-t commented
`docs\integration\multiplay.ngo.md` の 222 行目について。
`Dispose()` は自動で呼ばれることはなかったので修正が必要だと思います。

2023-01-12 09:02 UTC, sus-taguchi-t requested changes

2023-01-12 23:58 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/learning/chat.vivox.md
> +When joining a channel, we make the user log in if user is not already logged in.
When joining a channel, log in if the user is not logged in.
こんな感じでどうでしょうか？

2023-01-12 23:59 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-planning.md
> +  - CPU utilization/memory usage of the multiplayer server must be within a certain range, and there must be no memory leaks or other problems
そう思います。

2023-01-12 23:59 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/learning/core.md
> +Through this hands-on, you have already built the features required for [Extreal's assumed application architecture](/intro#application).
そう思います。

2023-01-13 00:56 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/learning/chat.vivox.md
> +When joining a channel, we make the user log in if user is not already logged in.
良いと思います！

2023-01-13 00:58 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-planning.md
> +  - CPU utilization/memory usage of the multiplayer server must be within a certain range, and there must be no memory leaks or other problems
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/33/commits/5e6cf37e8ff3d1322e359a70792a25df2b8037a9

2023-01-13 00:58 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/learning/core.md
> +Through this hands-on, you have already built the features required for [Extreal's assumed application architecture](/intro#application).
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/33/commits/374450dc8ccd762542eb12fa8ef565d3fdbc2086

2023-01-13 00:59 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/learning/chat.vivox.md
> +When joining a channel, we make the user log in if user is not already logged in.
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/33/commits/0f6ee0e9719bc106c9c058b7c7e143e63e55149b

2023-01-13 01:33 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/learning/chat.vivox.md
> +  - When joining a channel, if the user is not logged in, user logs in
ここも修正が必要でしょうか？

2023-01-13 01:33 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-planning.md
> +  - CPU utilization/memory usage of the multiplayer server must be within a certain range, and there must be no memory leaks or other problems
LGTM

2023-01-13 01:34 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/learning/chat.vivox.md
> +When joining a channel, we make the user log in if user is not already logged in.
LGTM

2023-01-13 01:35 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/learning/chat.vivox.md
> +  - When joining a channel, if the user is not logged in, user logs in
必要です。
すみません、忘れていました。

2023-01-13 01:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/learning/chat.vivox.md
> +  - When joining a channel, if the user is not logged in, user logs in
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/33/commits/d47c1ae212bb8467b261d85e90df8fb12af1788b

2023-01-13 01:40 UTC, sus-taguchi-t approved these changes

2023-01-13 01:40 UTC, merged