Refactoring AppUsage
extreal-dev/Extreal.Guide pull request #47
Opened 2023-06-13 14:45 UTC by kiyohome

﻿# 何の変更を加えましたか？

- https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/9 をHolidayのガイドに反映しました。

# 何を確認しましたか?

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました
- [ ] 日本語と英語のページが一致していることを確認しました
- [ ] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2023-06-15 10:31 UTC, sus-taguchi-t requested changes

2023-06-15 10:31 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +ログデータ送信を変更したい場合はAppUsageManager、IAppUsageCollectorを実装したクラス、AppUsageBase（またはサブクラス）の変更を検討してください。
この改修が英語版に反映されていないです。

2023-06-15 12:24 UTC, kiyohome commented on docs/sample-app/dev-guide.md
> +ログデータ送信を変更したい場合はAppUsageManager、IAppUsageCollectorを実装したクラス、AppUsageBase（またはサブクラス）の変更を検討してください。
すみません、修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/47/commits/33fa93e7238a010701ea23381303ab298448a69d

2023-06-16 00:05 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +ログデータ送信を変更したい場合はAppUsageManager、IAppUsageCollectorを実装したクラス、AppUsageBase（またはサブクラス）の変更を検討してください。
確認しました！

2023-06-16 06:37 UTC, sus-taguchi-t approved these changes

2023-06-16 06:37 UTC, merged