FW利用者がログ出力を使えるようにする
extreal-dev/Extreal.Guide pull request #5
Opened 2022-10-11 08:42 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

# What operation was verified? (なんの動作を確認しましたか?)

- [ ] ローカルPC上でyarn startしてブラウザで変更したページと影響がありそうなページを確認しました！

# Message to reviewers (レビュアーへのメッセージ)

2022-10-20 00:09 UTC, kiyohome commented on docs/core/logging.md
> +if (LOGGER.IsOutput(LogLevel.Debug)) {
ELoggerはログレベル毎にメソッドを分けた方が可読性が高かったように思います。慣れでしょうか？

2022-10-20 05:18 UTC, sus-taguchi-t requested changes

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +    }
引数にも型が必要だったと思います。
```mermaid
classDiagram
    class ELogger {
        -logCategory: string
        +IsOutput(logLevel: LogLevel) bool
        +Log(logLevel: LogLevel, message: string, exception: Exception = null) void
    }
```

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +```
仕様変更に伴って `ELogger` のメソッド名が変更になりました。

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +```
仕様変更に伴って `ELogger` のメソッド名が変更になりました。
またクラス名が `Logger` でなく `ELogger` です。

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +`https://github.com/extreal-dev/Extreal.Core.Logging.git`
ハイパーリンクは付けないのでしょうか？

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +    private static readonly ELogger LOGGER = LoggingManager.Get(nameof(SomethingService));
`LoggingManager.Get()` -> `LoggingManager.GetLogger()`

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +    }
仕様変更に伴って `ELogger` のメソッド名が変更になりました。
`LOGGER.Log()` -> `LOGGER.LogInfo()`

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +if (LOGGER.IsOutput(LogLevel.Debug)) {
同感です。
`ELogger` のメソッド名のみ以前の方式に戻しました。

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +```
仕様変更に伴って `ELogger` のメソッド名が変更になりました。
`LOGGER.IsOutput()` -> `LOGGER.IsDebug()`
`LOGGER.Log()` -> `LOGGER.LogDebug()`

2022-10-20 05:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +                break;
使用する `Exception` のクラスを変更予定です。
（`NotSupportedException` または `ArgumentOutOfRangeException` に変わる予定）

2022-10-20 05:54 UTC, kiyohome commented on docs/core/logging.md
> +    }
図が煩雑になるので型は書いてないんですが、あった方がいいですか？

2022-10-20 05:57 UTC, kiyohome commented on docs/core/logging.md
> +```
('◇')ゞ

2022-10-20 05:57 UTC, kiyohome commented on docs/core/logging.md
> +```
('◇')ゞ

2022-10-20 06:01 UTC, kiyohome commented on docs/core/logging.md
> +`https://github.com/extreal-dev/Extreal.Core.Logging.git`
使う人はURLをコピーすると思いハイパーリンクにしてないです。
あまりこのタイミングでGitHubに遷移する人はいないかなーと思っています。
サイトを訪れてソース見たい人はヘッダーの右端のGitHubリンクから、パッケージマネージャで使ってる人はローカルからソース見ると思ってました。

2022-10-20 06:01 UTC, kiyohome commented on docs/core/logging.md
> +    private static readonly ELogger LOGGER = LoggingManager.Get(nameof(SomethingService));
(^^ゞ

2022-10-20 06:01 UTC, kiyohome commented on docs/core/logging.md
> +    }
('◇')ゞ

2022-10-20 06:01 UTC, kiyohome commented on docs/core/logging.md
> +```
('◇')ゞ

2022-10-20 06:02 UTC, kiyohome commented on docs/core/logging.md
> +                break;
('◇')ゞ

2022-10-20 06:04 UTC, sus-taguchi-t commented on docs/core/logging.md
> +    }
仮引数名で何を使用するかは分かると思うので、なくても良いと思います！

2022-10-20 06:06 UTC, sus-taguchi-t commented on docs/core/logging.md
> +`https://github.com/extreal-dev/Extreal.Core.Logging.git`
分かりました。
ちなみにコピーする場合はバッククォートを 1 つで囲むよりも 3 つで囲った方が右端にコピーマークが出て良いかなと思いました。

2022-10-20 06:22 UTC, kiyohome commented on docs/core/logging.md
> +`https://github.com/extreal-dev/Extreal.Core.Logging.git`
ありがとうございます！
3つに変更します！

2022-10-20 06:47 UTC, kiyohome commented on docs/core/logging.md
> +```
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/5/commits/ac1415a84e572703580bb8af0742c45353e07307

2022-10-20 06:47 UTC, kiyohome commented on docs/core/logging.md
> +```
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/5/commits/ac1415a84e572703580bb8af0742c45353e07307

2022-10-20 06:47 UTC, kiyohome commented on docs/core/logging.md
> +    private static readonly ELogger LOGGER = LoggingManager.Get(nameof(SomethingService));
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/5/commits/ac1415a84e572703580bb8af0742c45353e07307

2022-10-20 06:47 UTC, kiyohome commented on docs/core/logging.md
> +    }
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/5/commits/ac1415a84e572703580bb8af0742c45353e07307

2022-10-20 06:48 UTC, kiyohome commented on docs/core/logging.md
> +```
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/5/commits/ac1415a84e572703580bb8af0742c45353e07307

2022-10-20 06:50 UTC, kiyohome commented on docs/core/logging.md
> +`https://github.com/extreal-dev/Extreal.Core.Logging.git`
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/5/commits/13c365eb1710e3f8ffafbc173e45331fdf1c3036

2022-10-21 00:58 UTC, sus-taguchi-t commented on docs/core/logging.md
> +```
確認しました！
問題ないです。

2022-10-21 00:59 UTC, sus-taguchi-t commented on docs/core/logging.md
> +```
確認しました！
問題ないです。

2022-10-21 02:00 UTC, sus-taguchi-t commented on docs/core/logging.md
> +`https://github.com/extreal-dev/Extreal.Core.Logging.git`
確認しました！
問題ないです。

2022-10-21 02:01 UTC, sus-taguchi-t commented on docs/core/logging.md
> +    }
確認しました！
問題ないです。

2022-10-21 02:02 UTC, sus-taguchi-t commented on docs/core/logging.md
> +```
確認しました！
問題ないです。

2022-10-21 02:12 UTC, kiyohome commented on docs/core/logging.md
> +                break;
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/5/commits/ffb468c63cb9a5a4d80a33c9f209f2c6e6db422b

2022-10-21 02:18 UTC, sus-taguchi-t commented on docs/core/logging.md
> +                break;
確認しました！
問題ないです。

2022-10-21 02:18 UTC, sus-taguchi-t approved these changes

2022-10-21 02:19 UTC, merged