WebGL/P2P
extreal-dev/Extreal.Guide pull request #50
Opened 2023-07-31 07:12 UTC by kiyohome

﻿# 何の変更を加えましたか？

- [ ] WebGL/P2P対応に合わせてガイドを変更

# 何を確認しましたか?

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました
- [ ] 日本語と英語のページが一致していることを確認しました
- [ ] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2023-08-10 09:37 UTC, sus-taguchi-t requested changes

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
書くところがなかったのでここに記述します。
`docs/intro.md` の変更に対応する英語側の変更が抜けています。

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/dev-guide.md
> +    - Processing common to P2P
ここ以降の変更が抜けています。

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> -  - Can return to avatar selection screen
`Can return to group selection screen`

が抜けています。

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> -    - Up/Down stream: 40 Mbps or higher
日本語版ではこれは残っています。

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> +    - Users are notified when the network is disconnected.
-> When the network is disconnected, the user is notified.

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-case.md
> +  - If Vivox (SaaS) fails and cannot respond to clients
Vivox (SaaS)
-> host side

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-case.md
>      - All features are available.
`.` の削除が抜けています。

2023-08-10 09:37 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-planning.md
>    - The server monitors CPU utilization/memory usage and determines passing criteria based on the data
```suggestion
  - Visually determine the application's acceptance criteria using PC at hand
  - Application CPU usage/memory usage is monitored and data is used to determine acceptance criteria
```

2023-08-17 07:31 UTC, kiyohome commented on docs/integration/chat.webrtc.md
> +```
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/52b0989f815061b6265e5b212208d8765008166b

2023-08-17 07:35 UTC, kiyohome commented on docs/integration/chat.webrtc.md
> +- [UniRx](https://github.com/neuecc/UniRx)
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/e7ceef6562cc38d3da37db31f7e8a451e1c4efc8

2023-08-17 07:39 UTC, kiyohome commented on docs/integration/chat.webrtc.md
> +- [@extreal-dev/extreal.integration.p2p.webrtc](https://www.npmjs.com/package/@extreal-dev/extreal.integration.p2p.webrtc)
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/3accf18b30753f21a8fa1f64e6b4e47437da12fe

2023-08-17 07:43 UTC, kiyohome commented on docs/integration/multiplay.ngo.md
> +- [WebRTC](https://docs.unity3d.com/Packages/com.unity.webrtc@3.0/manual/index.html)
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/5575fba1d96fad7224c443ca95370672cd0b00e4

2023-08-17 07:52 UTC, kiyohome commented on docs/integration/multiplay.ngo.md
> +    class WebRTCTransport {
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/5948ca18e97256784be9b195671af07ca81a3926

2023-08-17 07:57 UTC, kiyohome commented on docs/integration/multiplay.ngo.md
> +ホストの開始はStartServerAsyncを使います。
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/b43d4c86f45e821e895a1f0d6059186bb80c7484

2023-08-17 10:23 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +    PeerClientProvider ..> WebGLPeerClient
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/68a559b38844b05e1dd38bd8f3da9bbc8b9606f8

2023-08-17 10:28 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +    Signaling-->>Host: 409 "Host already exists"
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/eb8a58b58668cfcf106af4748566987283996257

2023-08-17 10:30 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +    Signaling-->>Client: 200 hosts list or empty list
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/51445c8c2a3f6f37d74b8d4833bd37963bb2acb4

2023-08-17 10:32 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +```
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/96b3ec326f4db1f8fad0707c2e46ef4356d57c75

2023-08-17 10:40 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +classDiagram
クラス図は主要なクラスの構造を示したいだけなので、Hostクラスは含めなくてもよいと思います。
Hostクラスは1つのメソッドの戻り値をまとめたデータの入れ物に過ぎないので。
クラス図を見てAPIの詳細を探す訳ではないですし、IDEの補完でHostクラスおよびプロパティは分かるのでクラス図で存在をアピールしなくてもよいと感じます。

2023-08-17 10:43 UTC, kiyohome commented on docs/release/unreleased.md
> +    - [UniRx](https://github.com/neuecc/UniRx) 7.1.0 ([MIT License](https://github.com/neuecc/UniRx/blob/master/LICENSE))
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/4dba16941844767c642730b402339b3d0f4d255d

2023-08-17 11:00 UTC, kiyohome commented on docs/release/unreleased.md
> +- P2P(Host/Client)によるマルチプレイができるWebRTCTransportを追加しました。([Doc](../integration/multiplay.ngo.md#mulitplay-ngo-p2p), [PR](https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/21))
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/1305af57034fa6c9144ae9675cc04526ff09fce7

2023-08-17 11:12 UTC, kiyohome commented on docs/release/unreleased.md
> +- ブラウザ向けのアプリケーション(WebGL)に変更しました。([Doc](../sample-app/requirements.md))
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/678ab1467c36f01e2a5010d3b0b4fa5d9a1c3a36

2023-08-17 11:22 UTC, kiyohome commented on docs/sample-app/test-case.md
>        - Cancelボタンでアバター選択画面に戻ること
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/139f370b59470d62d62e02eff4a39c1ed7ee71d1

2023-08-17 11:22 UTC, kiyohome commented on docs/sample-app/test-case.md
> +- グループ選択画面
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/139f370b59470d62d62e02eff4a39c1ed7ee71d1

2023-08-17 11:22 UTC, kiyohome commented on docs/sample-app/test-case.md
> +    - テキスト/ボイスチャット、マルチプレイは使用できること
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/139f370b59470d62d62e02eff4a39c1ed7ee71d1

2023-08-17 11:23 UTC, kiyohome commented on docs/sample-app/test-case.md
> +    - テキスト/ボイスチャット、マルチプレイは使用できること
P2Pで実現しているので～使用できない、に統一しました。

2023-08-17 11:27 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +Please add the following initialization after setting up P2P.WebRTC.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/b43d4c86f45e821e895a1f0d6059186bb80c7484

2023-08-17 11:34 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +WebRTC Settings](p2p.webrtc.md#settings) is required.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/13942a61568e0b443647226f9cd921e2f380d40b

2023-08-17 11:34 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +### Use NGO features for servers/hosts
Fixed!
https://github.com/extreal-dev/Extreal.Guide/commit/13942a61568e0b443647226f9cd921e2f380d40b

2023-08-17 11:35 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +- Reconnect when an NGO client disconnects.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/commit/13942a61568e0b443647226f9cd921e2f380d40b

2023-08-17 11:35 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +The created user becomes the host.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/commit/13942a61568e0b443647226f9cd921e2f380d40b

2023-08-17 11:36 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +When a host is shut down or a client leaves the host, the P2P connection is stopped.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/commit/13942a61568e0b443647226f9cd921e2f380d40b

2023-08-17 11:36 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +These hooks are used to manipulate data channels and media streams to add application-specific features to P2P.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/commit/13942a61568e0b443647226f9cd921e2f380d40b

2023-08-17 11:40 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/a00dae18a2f22db07e900ef5cfc13bbbf73d98d1

2023-08-17 11:44 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/dev-guide.md
> +    - Processing common to P2P
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/c17b542b6a783adb579426049b47069f97966007

2023-08-17 11:48 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> -  - Can return to avatar selection screen
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/eafeb966886ded61bfd28862f4cd5344194f84d5

2023-08-17 11:48 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> -    - Up/Down stream: 40 Mbps or higher
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/eafeb966886ded61bfd28862f4cd5344194f84d5

2023-08-17 11:53 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> +    - Users are notified when the network is disconnected.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/0c1a33d47cab7a0d124da39b053a2312c353f221

2023-08-17 11:54 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-case.md
> +  - If Vivox (SaaS) fails and cannot respond to clients
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/0c1a33d47cab7a0d124da39b053a2312c353f221

2023-08-17 11:54 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-case.md
>      - All features are available.
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/0c1a33d47cab7a0d124da39b053a2312c353f221

2023-08-17 11:54 UTC, kiyohome commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-planning.md
>    - The server monitors CPU utilization/memory usage and determines passing criteria based on the data
Fixed!
https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/0c1a33d47cab7a0d124da39b053a2312c353f221

2023-08-29 02:44 UTC, sus-taguchi-t commented on docs/integration/chat.webrtc.md
> +```
確認しました！

2023-08-29 02:45 UTC, sus-taguchi-t commented on docs/integration/chat.webrtc.md
> +- [UniRx](https://github.com/neuecc/UniRx)
確認しました！

2023-08-29 02:45 UTC, sus-taguchi-t commented on docs/integration/chat.webrtc.md
> +- [@extreal-dev/extreal.integration.p2p.webrtc](https://www.npmjs.com/package/@extreal-dev/extreal.integration.p2p.webrtc)
確認しました！

2023-08-29 02:46 UTC, sus-taguchi-t commented on docs/integration/multiplay.ngo.md
> +- [WebRTC](https://docs.unity3d.com/Packages/com.unity.webrtc@3.0/manual/index.html)
確認しました！

2023-08-29 02:46 UTC, sus-taguchi-t commented on docs/integration/multiplay.ngo.md
> +- [@extreal-dev/extreal.integration.p2p.webrtc](https://www.npmjs.com/package/@extreal-dev/extreal.integration.p2p.webrtc)
確認しました！

2023-08-29 02:49 UTC, sus-taguchi-t commented on docs/integration/multiplay.ngo.md
> +    class WebRTCTransport {
確認しました！

2023-08-29 02:52 UTC, sus-taguchi-t commented on docs/integration/multiplay.ngo.md
> +    class WebRTCTransport {
unreleased.md にも `WebRTCTransport` がありました。

2023-08-29 02:55 UTC, sus-taguchi-t commented on docs/integration/multiplay.ngo.md
> +次にWebRtcTransportにWebRTCClientを設定できるようにNgoServerとNgoClientを初期化します。
`WebRTCClient` -> `WebRtcClient`

他の場所も同様です。

2023-08-29 02:55 UTC, sus-taguchi-t commented on docs/integration/multiplay.ngo.md
> +ホストの開始はStartServerAsyncを使います。
確認しました！

2023-08-29 02:57 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +    PeerClientProvider ..> WebGLPeerClient
確認しました！

2023-08-29 02:58 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +    Signaling-->>Host: 409 "Host already exists"
確認しました！

2023-08-29 02:58 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +    Signaling-->>Client: 200 hosts list or empty list
確認しました！

2023-08-29 02:58 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +```
確認しました！

2023-08-29 02:59 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +classDiagram
分かりました！
そういう意図であれば問題ないと思います。

2023-08-31 00:41 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +    - [UniRx](https://github.com/neuecc/UniRx) 7.1.0 ([MIT License](https://github.com/neuecc/UniRx/blob/master/LICENSE))
確認しました！

2023-08-31 00:44 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- P2P(Host/Client)によるマルチプレイができるWebRTCTransportを追加しました。([Doc](../integration/multiplay.ngo.md#mulitplay-ngo-p2p), [PR](https://github.com/extreal-dev/Extreal.Integration.Multiplay.NGO/pull/21))
確認しました！

2023-08-31 00:45 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- ブラウザ向けのアプリケーション(WebGL)に変更しました。([Doc](../sample-app/requirements.md))
確認しました！

2023-08-31 00:45 UTC, sus-taguchi-t commented on docs/sample-app/test-case.md
>        - Cancelボタンでアバター選択画面に戻ること
確認しました！

2023-08-31 00:47 UTC, sus-taguchi-t commented on docs/sample-app/test-case.md
> +- グループ選択画面
確認しました！

2023-08-31 00:49 UTC, sus-taguchi-t commented on docs/sample-app/test-case.md
> +    - テキスト/ボイスチャット、マルチプレイは使用できること
確認しました！

2023-08-31 00:50 UTC, sus-taguchi-t commented on docs/sample-app/test-case.md
>    - マルチプレイサーバで障害が発生しクライアントに応答できない場合
確認しました！

2023-08-31 00:51 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/chat.webrtc.md
> +Text chat is realized using [P2P.WebRTC](p2p.webrtc.md) for P2P.
確認しました！

2023-08-31 00:51 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +WebRTC Settings](p2p.webrtc.md#settings) is required.
確認しました！

2023-08-31 00:51 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +Please add the following initialization after setting up P2P.WebRTC.
確認しました！

2023-08-31 00:52 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +### Use NGO features for servers/hosts
確認しました！

2023-08-31 00:53 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/multiplay.ngo.md
> +### Add processing to trigger NGO servers/hosts state
確認しました！

2023-08-31 01:35 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +The created user becomes the host.
確認しました！

2023-08-31 01:36 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +When a host is shut down or a client leaves the host, the P2P connection is stopped.
確認しました！

2023-08-31 01:38 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +These hooks are used to manipulate data channels and media streams to add application-specific features to P2P.
すみません、1 点指摘ミスがありました。

functionality -> features

2023-08-31 01:41 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
確認しました！

2023-08-31 01:54 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/dev-guide.md
> +    - Processing common to P2P
549 行目あたりの変更も抜けています。

2023-08-31 01:55 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> -  - Can return to avatar selection screen
確認しました！

2023-08-31 01:56 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> -    - Up/Down stream: 40 Mbps or higher
確認しました！

2023-08-31 01:57 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/requirements.md
> +    - Users are notified when the network is disconnected.
確認しました！

2023-08-31 01:57 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-case.md
> +  - If Vivox (SaaS) fails and cannot respond to clients
確認しました！

2023-08-31 01:58 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-case.md
>      - All features are available.
確認しました！

2023-08-31 01:58 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/test-planning.md
>    - The server monitors CPU utilization/memory usage and determines passing criteria based on the data
確認しました！

2023-09-04 00:54 UTC, mahaweilu commented on docs/integration/multiplay.ngo.md
> +次にWebRtcTransportにWebRTCClientを設定できるようにNgoServerとNgoClientを初期化します。
fixed https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/f98ed45a1d1eb9d9a1c9c43586c1908dd85617cf

2023-09-05 06:23 UTC, kiyohome commented on docs/integration/asset-workflow.addressables.md
> +ResourceProviderの設定で関連するクラスを利用するため、`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`の命名空間をアアプリケーションの`Assembly Definition References`に追加する必要があります。
Assembly Definitionへの追加はもともとガイドで言及していないので、Packageのところでinfoで追記した方がいいと思います。
PackageのURL見てPackage Managerからパッケージをimport後にAssembly Definitionに追加すると思うので。

以下のような感じです。
----
アセットの暗号化と復号機能はWebGLで使えないためネームスペースを分け、プラットフォームからWebGLを除外しています。そのためアセットの暗号化と復号機能を使う場合は`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`をAssembly Definitionに追加してください。

2023-09-05 06:23 UTC, kiyohome commented on docs/integration/asset-workflow.addressables.md
> +ResourceProviderの設定で関連するクラスを利用するため、`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`の命名空間をアアプリケーションの`Assembly Definition References`に追加する必要があります。
英語ページも更新をお願いします。

2023-09-05 06:23 UTC, kiyohome commented on docs/integration/asset-workflow.addressables.md
> +ResourceProviderの設定で関連するクラスを利用するため、`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`の命名空間をアアプリケーションの`Assembly Definition References`に追加する必要があります。
後方互換崩れているのでReleaseページに変更内容と後方互換を追記してください。

2023-09-06 08:33 UTC, kiyohome commented on docs/integration/asset-workflow.addressables.md
> +AssetProvider.GetDownloadSizeAsyncメソッドは、アセットがキャッシュされている場合0を返しますが、
「・・・場合0を・・・」
「・・・場合は0を・・・」の方がよくないでしょうか。

2023-09-06 08:33 UTC, kiyohome commented on docs/integration/asset-workflow.addressables.md
> +[Unity Forum](https://forum.unity.com/threads/in-2022-2-xx-webgl-builds-getdownloadsizeasync-does-not-reflect-the-cache.1440877/)に投稿されている通り、
下記のような感じはどうでしょうか。
----
この動作は、Addressables.GetDownloadSizeAsyncメソッドの仕様によるものです。詳細は[Unity Forum](https://forum.unity.com/threads/in-2022-2-xx-webgl-builds-getdownloadsizeasync-does-not-reflect-the-cache.1440877/)を参照ください。

2023-09-06 08:58 UTC, sasuke9410 commented on docs/integration/asset-workflow.addressables.md
> +AssetProvider.GetDownloadSizeAsyncメソッドは、アセットがキャッシュされている場合0を返しますが、
Fixed 60e725e295fc258b477b629d684fb89a0aae0f9a

2023-09-06 08:58 UTC, sasuke9410 commented on docs/integration/asset-workflow.addressables.md
> +[Unity Forum](https://forum.unity.com/threads/in-2022-2-xx-webgl-builds-getdownloadsizeasync-does-not-reflect-the-cache.1440877/)に投稿されている通り、
Fixed 60e725e295fc258b477b629d684fb89a0aae0f9a
英語ドキュメントも合わせて修正しました。

2023-09-07 07:26 UTC, mahaweilu commented on docs/integration/asset-workflow.addressables.md
> +ResourceProviderの設定で関連するクラスを利用するため、`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`の命名空間をアアプリケーションの`Assembly Definition References`に追加する必要があります。
対応しました。

https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/e30b9f4ee51cef126c50e6be944a2077c4da626f

2023-09-08 01:41 UTC, mahaweilu commented on docs/integration/asset-workflow.addressables.md
> +ResourceProviderの設定で関連するクラスを利用するため、`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`の命名空間をアアプリケーションの`Assembly Definition References`に追加する必要があります。
伊藤さんと一緒に対面で確認しました。

2023-09-08 02:16 UTC, mahaweilu commented on docs/integration/asset-workflow.addressables.md
> +ResourceProviderの設定で関連するクラスを利用するため、`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`の命名空間をアアプリケーションの`Assembly Definition References`に追加する必要があります。
伊藤さんと一緒に対面で確認しました。

https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/c675b46f5e7dc0a472c6a4093715de575a035699

2023-09-08 02:18 UTC, mahaweilu commented on docs/integration/asset-workflow.addressables.md
> +ResourceProviderの設定で関連するクラスを利用するため、`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`の命名空間をアアプリケーションの`Assembly Definition References`に追加する必要があります。
伊藤さんと一緒に対面で確認しました。

https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/8ed8c6a7b646f27b202f368ac15652a658e2b157

https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/c675b46f5e7dc0a472c6a4093715de575a035699

2023-09-08 08:20 UTC, mahaweilu commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/dev-guide.md
> +    - Processing common to P2P
fixed

https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/22518b7bdf1885902da4f63caaaed19627b9c274

2023-09-08 08:21 UTC, mahaweilu commented on docs/integration/multiplay.ngo.md
> +    class WebRTCTransport {
fixed https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/4fe26fd2bf4388ab3f523487b822197ee4ff62e9

2023-09-08 08:22 UTC, mahaweilu commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +These hooks are used to manipulate data channels and media streams to add application-specific features to P2P.
fixed 

https://github.com/extreal-dev/Extreal.Guide/pull/50/commits/1cb6fd0f23bcf7599afa5356c6e96817b7a7fec9

2023-09-08 08:34 UTC, sus-taguchi-t commented on docs/integration/multiplay.ngo.md
> +    class WebRTCTransport {
確認しました！

2023-09-08 08:34 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +These hooks are used to manipulate data channels and media streams to add application-specific features to P2P.
確認しました！

2023-09-08 08:35 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/sample-app/dev-guide.md
> +    - Processing common to P2P
確認しました！

2023-09-08 08:49 UTC, sus-taguchi-t approved these changes

2023-09-08 08:49 UTC, merged