Massively Multiplay モジュールを追加
extreal-dev/Extreal.Guide pull request #56
Opened 2023-11-28 07:55 UTC by sus-taguchi-t

﻿# 何の変更を加えましたか？

- Holiday のガイドを修正しました 
  - P2Pマルチプレイ以外に、Redis(PubSub)マルチプレイもできるように修正
- Massively Multiplay モジュールのガイドを追加しました
  - ~Multiplay.Common~ [Multiplay.Messaging](https://github.com/extreal-dev/Extreal.Integration.Multiplay.Messaging)
  - ~Messaging.Common~ [Messaging](https://github.com/extreal-dev/Extreal.Integration.Messaging)
  - [Messaging.Socket.IO](https://github.com/extreal-dev/Extreal.Integration.Messaging.Socket.IO)
- Core/Integration 内のモジュールのインデックスを辞書順になるように並べ替えました

# 何を確認しましたか?

- [x] 変更したページと影響がありそうなページをブラウザで確認しました
- [x] 日本語と英語のページが一致していることを確認しました
  - 英語版は別PRで対応(ToDo有)
- [x] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2023-12-14 05:37 UTC, mahaweilu commented on docs/integration/messaging.redis.md
> +
[p2pの時](https://extreal-dev.github.io/Extreal.Guide/integration/p2p.webrtc#%E3%82%B7%E3%82%B0%E3%83%8A%E3%83%AA%E3%83%B3%E3%82%B0%E3%82%B5%E3%83%BC%E3%83%90)と同じように、Settingsに簡単でもRedisサーバーのことを記載した方が良いと思いましたがどうですか？

2023-12-14 06:42 UTC, sus-yoshikane-t requested changes

2023-12-14 06:42 UTC, sus-yoshikane-t commented on docs/img/holiday-app-structure.png
赤波線が表示されてしまっています。

2023-12-15 02:34 UTC, sus-taguchi-t commented on docs/img/holiday-app-structure.png
ありがとうございます！
修正します。

2023-12-15 02:34 UTC, sus-taguchi-t commented on docs/integration/messaging.redis.md
> +
その通りですね。
追記します！

2023-12-15 02:43 UTC, sus-taguchi-t commented on docs/img/holiday-app-structure.png
修正しました！
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/b9b0cc1290b395dd3ec06f5879bada148bdaca77

2023-12-15 02:58 UTC, sus-taguchi-t commented on docs/integration/messaging.redis.md
> +
追記しました！
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/1b274dcb61490153d00821cd99854648c0ef46d3

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +[Messaging.CommonのUsage](messaging.common.md#Usage)を参照してください。
通信方式の変更方法は Specification に記載したのでそちらへのリンクをお願いします。

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +SpawnPlayerメソッドを使って、全プレイヤーをスポーンします。
「全プレイヤー」とは何でしょうか？

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +```
SpawnObject メソッドはスポーンさせたいオブジェクトを指定しないと呼び出せないです。

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +同期されるオブジェクトにアタッチされたMultiplayerInputのValuesの値を同期しています。
MultiplayerInput -> MultiplayPlayerInput

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +同期されたValuesをSetValuesメソッドを使ってローカルオブジェクトに適用します。
同期されたValuesを -> 同期されたValuesは

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +### プレイヤーへの入力情報を同期する
同期する/しないの制御ができることもここで触れた方が良いと思います。

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +## Specification
IObserber なプロパティに Subscribe できることにも触れた方が良いと思います。

2023-12-15 05:36 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +メッセージ受信はOnMessageReceivedイベントを使います。 パラメータとしてユーザ識別子とJSONのメッセージが渡ってきます。
受信したメッセージが JSON かどうかはアプリ要件なのでここでは触れたくないです。

2023-12-15 06:16 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +- ホスト/サーバーが[NGOラッパー](multiplay.ngo.md)以外の外部ライブラリから構築します。
「ホスト/サーバーを～から構築します。」にしました。ありがとうございます！

2023-12-15 06:27 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +SpawnPlayerメソッドを使って、全プレイヤーをスポーンします。
接続中のプレイヤーのつもりでしたが、プレイヤーって表現だけで良いか今思ってきました。修正しました。

2023-12-15 06:32 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +SpawnPlayerメソッドを使って、全プレイヤーをスポーンします。
修正しました。

2023-12-15 06:32 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +[Messaging.CommonのUsage](messaging.common.md#Usage)を参照してください。
修正しました。

2023-12-15 06:32 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +- ホスト/サーバーとの通信方式を変更（[Messaging.Common](messaging.common.md)を利用）できます。
修正しました。

2023-12-15 06:32 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +- ホスト/サーバーとの通信方式を変更（[Messaging.Common](messaging.common.md)を利用）できます。
修正しました。

2023-12-15 06:32 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。そのため、大規模なマルチプレイを実現する場合、ホスト/サーバーに膨大な負荷がかかり、コストが高くなります。
修正しました。

2023-12-15 06:32 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。そのため、大規模なマルチプレイを実現する場合、ホスト/サーバーに膨大な負荷がかかり、コストが高くなります。
修正しました。

2023-12-15 06:33 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +```
修正しました。

2023-12-15 06:34 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +同期されるオブジェクトにアタッチされたMultiplayerInputのValuesの値を同期しています。
修正しました。

2023-12-15 06:34 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +同期されたValuesをSetValuesメソッドを使ってローカルオブジェクトに適用します。
修正しました。

2023-12-15 06:37 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +### プレイヤーへの入力情報を同期する
修正しました。

2023-12-15 06:57 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +## Specification
修正しました。

2023-12-15 07:01 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +メッセージ受信はOnMessageReceivedイベントを使います。 パラメータとしてユーザ識別子とJSONのメッセージが渡ってきます。
修正しました。

2023-12-15 07:02 UTC, mahaweilu commented on docs/integration/messaging.redis.md
> +
確認しました。

2023-12-15 07:46 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。そのため、大規模なマルチプレイを実現する場合、ホスト/サーバーに膨大な負荷がかかり、コストが高くなります。
段落を分ける必要はないと思います。

2023-12-15 07:48 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。そのため、大規模なマルチプレイを実現する場合、ホスト/サーバーに膨大な負荷がかかり、コストが高くなります。
確認しました。

2023-12-15 07:48 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +- ホスト/サーバーとの通信方式を変更（[Messaging.Common](messaging.common.md)を利用）できます。
確認しました。

2023-12-15 07:48 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +- ホスト/サーバーとの通信方式を変更（[Messaging.Common](messaging.common.md)を利用）できます。
確認しました。

2023-12-15 07:49 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +[Messaging.CommonのUsage](messaging.common.md#Usage)を参照してください。
確認しました。

2023-12-15 07:50 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +SpawnPlayerメソッドを使って、全プレイヤーをスポーンします。
読点はない方が読みやすくなると思います。

2023-12-15 07:52 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +```
基本的にスポーンさせるオブジェクトはプレハブにすると思うので、コメントアウトされた注釈は不要だと思います。
渡す変数名も `objectPrefab` や `objectToBeSpawned` のように分かりやすくしたいです。

2023-12-15 07:53 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +同期されるオブジェクトにアタッチされたMultiplayerInputのValuesの値を同期しています。
確認しました。

2023-12-15 07:53 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +同期されたValuesをSetValuesメソッドを使ってローカルオブジェクトに適用します。
確認しました。

2023-12-15 07:58 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +### プレイヤーへの入力情報を同期する
もう少し詳しく伝えたいです。
またその場合「同期する入力情報を拡張する方法」と「同期するかどうかを制御する方法」でそれぞれ例示するコードを分けたいです。

2023-12-15 08:04 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +## Specification
「Messaging.Commonのイベント通知」だと曖昧で分からないです。
もっと明確に「MessagingClientのイベント通知」まで言い切った方が良いです。

2023-12-15 08:07 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +メッセージ受信はOnMessageReceivedイベントを使います。 パラメータとしてユーザ識別子とJSONのメッセージが渡ってきます。
https://github.com/extreal-dev/Extreal.Guide/pull/56#discussion_r1427619938

こちらの修正で OnMessageReceived イベントについて記述されているのでここで触れる必要はなくなったと思います。
ここの項目は「メッセージ送信」だけで良いのではないでしょうか？

2023-12-15 08:41 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。そのため、大規模なマルチプレイを実現する場合、ホスト/サーバーに膨大な負荷がかかり、コストが高くなります。
対応しました。　[322e1d5](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/322e1d514d7dd3658f78cb606b2fc19a6e68f765)

2023-12-15 09:20 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +メッセージ受信はOnMessageReceivedイベントを使います。 パラメータとしてユーザ識別子とJSONのメッセージが渡ってきます。
受送信とクライアント状態のトリガーは分類？用途が違うため明確に分けたほうが良いと思います。「受信はmessagingClientの受信イベントを参考してね」って雰囲気で修正しまたがどうですか？

[3a0a3dc](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/3a0a3dc4999b02ec151a1a3f12a2881ff0ee36af)

2023-12-15 09:21 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +## Specification
https://github.com/extreal-dev/Extreal.Guide/pull/56#discussion_r1427672275　に合わせて修正しました。　[3a0a3dc](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/3a0a3dc4999b02ec151a1a3f12a2881ff0ee36af)

2023-12-15 09:26 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +SpawnPlayerメソッドを使って、全プレイヤーをスポーンします。
ありがとうございます。　[d45532b](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/d45532bf9db331de9ec4c7d469d2e8b5e6576af1)

2023-12-15 09:31 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +```
修正しました。　[e314b98](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/e314b98e072280b224b1ef6c3a76cfe6ed4ae4a3)

2023-12-18 01:23 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。そのため、大規模なマルチプレイを実現する場合、ホスト/サーバーに膨大な負荷がかかり、コストが高くなります。
確認しました。

2023-12-18 01:23 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +SpawnPlayerメソッドを使って、全プレイヤーをスポーンします。
確認しました。

2023-12-18 01:24 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +```
確認しました。

2023-12-18 01:26 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +### プレイヤーへの入力情報を同期する
確認しました。

2023-12-18 01:28 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +## Specification
確認しました。

2023-12-18 01:44 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +メッセージ受信はOnMessageReceivedイベントを使います。 パラメータとしてユーザ識別子とJSONのメッセージが渡ってきます。
対面で話して以下のように修正しました。

[86c490d](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/86c490d78ea3c5ea968596f732ccd874eacc69fd)

2023-12-18 01:51 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +メッセージ受信はOnMessageReceivedイベントを使います。 パラメータとしてユーザ識別子とJSONのメッセージが渡ってきます。
追加で、以下修正も加えています。

[5214cb8](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/5214cb868a3b28d5c6f50e8cd45230c7479c93ee)

[996ec23](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/996ec23f622e6c05cbe5c64e5b6321c5006b990e)

2023-12-18 01:52 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +メッセージ受信はOnMessageReceivedイベントを使います。 パラメータとしてユーザ識別子とJSONのメッセージが渡ってきます。
確認しました。

2023-12-18 01:52 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +## Specification
対面で話して以下のように修正しました。

[86c490d](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/86c490d78ea3c5ea968596f732ccd874eacc69fd)

2023-12-18 04:03 UTC, sus-yoshikane-t commented on docs/integration/multiplay.common.md
> +- ホスト/サーバーが[NGOラッパー](multiplay.ngo.md)以外の外部ライブラリから構築します。
確認しました。

2023-12-18 04:03 UTC, sus-yoshikane-t commented on docs/img/holiday-app-structure.png
確認しました。

2023-12-18 09:21 UTC, kiyohome requested changes

2023-12-18 09:21 UTC, kiyohome commented on docs/integration/multiplay.common.md
> +SpawnObjectメソッドを使ってレイヤー以外のオブジェクトをスポーンします。
レイヤー　→　プレイヤー

2023-12-18 09:21 UTC, kiyohome commented on docs/integration/multiplay.common.md
> +### グループへの入退室を行う
こちらも全体的にUsageの繋がりがよく分からないので、使い方がよく分からないです。

2023-12-18 09:21 UTC, kiyohome commented on docs/integration/multiplay.common.md
> +同期されるオブジェクトにアタッチされたMultiplayPlayerInputのValuesの値を同期しています。
「同期されるオブジェクトにアタッチされたMultiplayPlayerInputのValuesの値」とは？

2023-12-18 09:21 UTC, kiyohome commented on docs/intro.md
> +  - [Chat using WebRTC](./integration/chat.webrtc.md)
ここの順番はアルファベット順にしませんか？

2023-12-18 09:21 UTC, kiyohome commented on docs/release/1.1.0.md
> +
これは何の変更ですか？

2023-12-18 09:21 UTC, kiyohome commented on docs/intro.md
> +  - [Chat using WebRTC](./integration/chat.webrtc.md)
Frameworkの図は更新しないですか？
https://github.com/extreal-dev/Extreal.Guide/blob/d68eac48ccaa5184ffab6ee8bc4d4710c138537a/docs/img/fw-arch.png

2023-12-18 09:21 UTC, kiyohome commented on docs/release/unreleased.md
> +2024-01-30
リリース日と思われるので、更新日にしてください。
1月末を予定していますが確定ではありません。

2023-12-18 09:21 UTC, kiyohome commented on docs/release/unreleased.md
> +- [@extreal-dev/extreal.integration.messaging.redis](https://www.npmjs.com/package/@extreal-dev/extreal.integration.messaging.redis) 1.0.0-Next.1
nextは小文字ではないでしょうか？

https://github.com/extreal-dev/Extreal.Ops?tab=readme-ov-file#%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81

2023-12-18 09:21 UTC, kiyohome commented on docs/release/unreleased.md
> +- PeerConnectionのCreate/Closeでエラーが発生しても処理を継続するように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/9))
モジュール名がないですね。

2023-12-18 09:21 UTC, kiyohome commented on docs/release/unreleased.md
> +- マルチプレイで使用する共通機能を追加しました。([Doc](../integration/multiplay.common.md))
リリースノートの記載は、モジュールやサンプルアプリのレビュー対応後に、再度見直してください。

2023-12-19 00:27 UTC, sus-taguchi-t commented on .markdownlint.json
> +    "MD013": false,
>falseってチェックを除外している設定ですか？

除外している設定であっています。

>基本はできるだけチェックを除外しない方がいいと思いますが、除外している理由はありますか？

理由は以下です。

- `MD013`: 1 行当たりの文字数を制限するものですが、途中で改行しない方が書きやすい/読みやすいと思ったので除外しました。
- `MD024`: 同じ文言のヘッダを 2 つ以上同じファイル内に記述させないものですが、状況次第で同じヘッダを記述するときがあったので除外しました。
- `MD031`: バッククォート 3 つで囲まれたブロックの前後を空行で囲ませるものですが、今見直すと除外する必要はないためこれは true に戻します。

>あとMarkDownはあまりLintかけたことありませんが、かけた方がいいですか？

フォーマッタを自動でかけてくれたりして便利だったので導入していました。
しかし基本的に整形以上の意味はないので導入しなくても良いと思います。

2023-12-19 00:34 UTC, sus-taguchi-t commented on docs/core/common.md
> +sidebar_position: 1
すみません、書いていなかったです。
追記しました。

2023-12-19 00:56 UTC, sus-taguchi-t commented on docs/core/common.md
> +sidebar_position: 1
すみません、書いていなかったです。
追記しました。

2023-12-19 00:59 UTC, sus-taguchi-t commented on docs/sample-app/intro.md
> +HolidayはRedisのPub/Sub(Publish/Subscribe)およびP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
こちらは「ホスト/クライアントを選択できる」と「大規模/軽量（用語は要検討）を選択できる」に分けて記述します。

2023-12-19 01:00 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - 大規模または軽量を選択できる
用語の認識を合わせた後、SampleApp の Intro に追記します。

2023-12-19 01:04 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +    - テキスト/ボイスチャット以外の機能は使用できる。
できないです。
massively で P2P チャットを使用してしまっていること自体が良くないと思っているのでそこから認識併せたいです。

2023-12-19 01:26 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +- キューイングを行うことができます。
「メッセージを送信したり、受信したメッセージを取り扱うタイミングを制御できるようになる」という認識です。

2023-12-19 02:01 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +        +SetMessagingClient(messagingClient) void
MonoBehaviour を継承しているのでコンストラクタで渡すことはできないです。

2023-12-19 02:17 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +同期されるオブジェクトにアタッチされたMultiplayPlayerInputのValuesの値を同期しています。
memo:「プレイヤーへの入力情報」をMultiplayPlayerInputValuesで保持しています。この値をユーザ間で同期しています

2023-12-19 02:19 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +同期されたValuesはSetValuesメソッドを使ってローカルオブジェクトに適用します。
memo:ローカルオブジェクトの概念を追加する

2023-12-19 02:22 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +Move以外に他の入力情報を同期したい場合、MultiplayPlayerInputとMultiplayPlayerInputValuesを継承したクラスを作成し、Valuesにセットするようにします。
memo（Usage流れ）:
-「プレイヤーへの入力情報」をMultiplayPlayerInputValuesで保持しています。
- この値をユーザ間で同期しています
- デフォルトではMoveのみ同期しています。

2023-12-19 05:37 UTC, sus-taguchi-t commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
メッセージングサーバ経由

2023-12-19 05:41 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +- キューイングを行うことができます。
メッセージを扱うタイミングを制御（キューイング）できます。

2023-12-19 05:45 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +GroupManagerクラスを使用することでグループを管理できます。
Create/Delete にする（groupName 指定）

2023-12-19 06:01 UTC, sus-taguchi-t commented on .markdownlint.json
> +    "MD013": false,
Lint を削除します。

2023-12-19 06:02 UTC, sus-taguchi-t commented on docs/sample-app/intro.md
> +HolidayはRedisのPub/Sub(Publish/Subscribe)およびP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
サンプルを分けるのでここの説明は不要になります。

2023-12-19 06:02 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - 大規模または軽量を選択できる
サンプルを分けるのでここの説明は不要になります。

2023-12-19 06:02 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +    - テキスト/ボイスチャット以外の機能は使用できる。
サンプルを分けるのでここの対応は不要になります。

2023-12-19 06:03 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - 日本、日本語のみ
Lint による自動フォーマッタです。
削除します。

2023-12-19 06:04 UTC, sus-taguchi-t commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
サンプルを分けるのでここの対応は不要になります。

2023-12-19 06:07 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +グループでメッセージのやり取りをする機能の共通部分を提供します。
モジュール名を `Messaging` にしてドキュメントは 1 つにします。

2023-12-19 06:08 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +この共通機能を使うことで自由にバックエンドとの通信方式を切り替えることができるようになります。
その通りだと思います。
修正します。

2023-12-19 06:08 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +また使い方次第でマルチプレイにおける同期メッセージのやりとりやテキストチャットなど様々な用途に活用できます。
その通りだと思います。
修正します。

2023-12-19 06:09 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +        +SetTransport(transport) void
あまり強い理由はないです。
コンストラクタに変更します。

2023-12-19 06:11 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +存在するグループ一覧を取得するためにはListGroupsAsyncを使います。
その通りだと思います。
修正します。

2023-12-19 06:12 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +受信したメッセージをハンドリングします。
その通りだと思います。
修正します。

2023-12-19 06:12 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +このモジュールは通信に使用するトランスポートを変更できます。
その通りだと思います。
修正します。

2023-12-19 06:14 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +    class IMessagingTransport {
共通の抽象クラス MessagingClient を作成して、それを継承したクラスとして RedisMessagingClient を作成します。

2023-12-19 06:14 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +MessagingClientは上記に加えて次のイベント通知を設けています。
その通りだと思います。
修正します。

2023-12-19 06:14 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +OnDisconnectingとOnUnexpectedDisconnectedで受け取れるパラメータはトランスポートで実装しています。
その通りだと思います。
修正します。

2023-12-19 06:14 UTC, sus-taguchi-t commented on docs/integration/messaging.common.md
> +Extrealで提供しているデフォルトのトランスポートを再掲します。
その通りだと思います。
修正します。

2023-12-19 06:15 UTC, sus-taguchi-t commented on docs/integration/messaging.redis.md
> +# Messaging using Redis
その通りだと思います。
修正します。

2023-12-19 06:15 UTC, sus-taguchi-t commented on docs/integration/messaging.redis.md
> +#### Redisサーバ
その通りだと思います。
修正します。

2023-12-19 06:19 UTC, sus-taguchi-t commented on docs/integration/messaging.redis.md
> +Redisサーバは[Docker Compose](https://docs.docker.com/compose/)で提供しています。
Redisサーバ -> メッセージングサーバ

サーバ・クライアント間はSocket.IOで接続し、Pub/SubはRedisのアダプターで実現しています。
詳細は[Redis adapter](https://socket.io/docs/v4/redis-adapter/)および[Rooms](https://socket.io/docs/v4/rooms/)を参照してください。

2023-12-19 06:20 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。
その通りだと思います。
修正します。

2023-12-19 06:21 UTC, sus-taguchi-t commented on docs/integration/multiplay.common.md
> +# Common for Multiplay
モジュール名を `Multiplay.Messaging` に変更します。

2023-12-19 11:25 UTC, mahaweilu commented on .markdownlint.json
> +    "MD013": false,
対応しました。[0ca1ebe](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/0ca1ebeb4a2ebe0627875ee551f8dc36455ce92d)

2023-12-19 12:42 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +グループでメッセージのやり取りをする機能の共通部分を提供します。
モジュール名を変更しました。[9222e8c](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9222e8c5372adcb5786acd317262d3cc764df477)

指摘を対応した変更箇所が見やすいように、ファイル名は指摘対応を確認していたたいてから変更しようと思います。

2023-12-19 12:42 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +この共通機能を使うことで自由にバックエンドとの通信方式を切り替えることができるようになります。
修正しました。[9222e8c](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9222e8c5372adcb5786acd317262d3cc764df477)

2023-12-19 12:43 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +また使い方次第でマルチプレイにおける同期メッセージのやりとりやテキストチャットなど様々な用途に活用できます。
修正しました。[9222e8c](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9222e8c5372adcb5786acd317262d3cc764df477)

2023-12-19 12:47 UTC, mahaweilu commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
修正しました。[3f3a75d](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/3f3a75de37d4ec2cfbefae1e26a364cf03ee625c)

2023-12-19 12:48 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +- キューイングを行うことができます。
修正しました。[3f3a75d](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/3f3a75de37d4ec2cfbefae1e26a364cf03ee625c)

2023-12-19 13:20 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +存在するグループ一覧を取得するためにはListGroupsAsyncを使います。
specificationから全体的な流れを読み取れやすいように修正しました。[f89a3bc](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/f89a3bc77995ec0bbd65b95db48e88217faba799)

2023-12-22 07:52 UTC, mahaweilu commented on docs/sample-app/intro.md
> +HolidayはRedisのPub/Sub(Publish/Subscribe)およびP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
Holidayに関する修正は以下で修正しました。
[7d1184b](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7d1184bc444a1ecd1caf739729800c59869ab8b1)

2023-12-22 07:52 UTC, mahaweilu commented on docs/sample-app/requirements.md
> +  - 大規模または軽量を選択できる
Holidayに関する修正は以下で修正しました。
[7d1184b](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7d1184bc444a1ecd1caf739729800c59869ab8b1)

2023-12-22 07:52 UTC, mahaweilu commented on docs/sample-app/requirements.md
> +    - テキスト/ボイスチャット以外の機能は使用できる。
Holidayに関する修正は以下で修正しました。
[7d1184b](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7d1184bc444a1ecd1caf739729800c59869ab8b1)

2023-12-22 07:53 UTC, mahaweilu commented on docs/sample-app/requirements.md
> +  - 日本、日本語のみ
Holidayに関する修正は以下で修正しました。
[7d1184b](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7d1184bc444a1ecd1caf739729800c59869ab8b1)

2023-12-22 07:53 UTC, mahaweilu commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
Holidayに関する修正は以下で修正しました。
[7d1184b](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7d1184bc444a1ecd1caf739729800c59869ab8b1)

2023-12-22 07:53 UTC, mahaweilu commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
Holidayに関する修正は以下で修正しました。
[7d1184b](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7d1184bc444a1ecd1caf739729800c59869ab8b1)

2023-12-22 08:02 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +グループでメッセージのやり取りをする機能の共通部分を提供します。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:03 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +この共通機能を使うことで自由にバックエンドとの通信方式を切り替えることができるようになります。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:03 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +また使い方次第でマルチプレイにおける同期メッセージのやりとりやテキストチャットなど様々な用途に活用できます。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:04 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +        +SetTransport(transport) void
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:04 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +GroupManagerクラスを使用することでグループを管理できます。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:04 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +存在するグループ一覧を取得するためにはListGroupsAsyncを使います。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:05 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +受信したメッセージをハンドリングします。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:05 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +このモジュールは通信に使用するトランスポートを変更できます。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:05 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +    class IMessagingTransport {
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:05 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +MessagingClientは上記に加えて次のイベント通知を設けています。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:06 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +OnDisconnectingとOnUnexpectedDisconnectedで受け取れるパラメータはトランスポートで実装しています。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:07 UTC, mahaweilu commented on docs/integration/messaging.common.md
> +Extrealで提供しているデフォルトのトランスポートを再掲します。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:07 UTC, mahaweilu commented on docs/integration/messaging.redis.md
> +# Messaging using Redis
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:07 UTC, mahaweilu commented on docs/integration/messaging.redis.md
> +#### Redisサーバ
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:07 UTC, mahaweilu commented on docs/integration/messaging.redis.md
> +Redisサーバは[Docker Compose](https://docs.docker.com/compose/)で提供しています。
messaging.commonとmessaging.redisを合体させ、構成も大きく変わりました。お手数ですがmessagingに関する指摘対応は以下から、messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:10 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +この同期処理は[NGOラッパー](multiplay.ngo.md)を利用し実現する場合、ホスト/サーバーが中心となって行われます。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:10 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +# Common for Multiplay
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:10 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +そのため、大規模なマルチプレイを実現する場合、ホスト/サーバーに膨大な負荷がかかり、高いマシンスペックが必要になります。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:10 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +このライブラリでは低コストで大規模なマルチプレイができるように、以下の特徴を持った機能を提供します。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:10 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +- 通信方式を変更できます。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:11 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +        +SetMessagingClient(messagingClient) void
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:11 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +- グループへの入退室ができます。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:11 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +await extrealMultiplayClient.ConnectAsync(connectionConfig);
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:11 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +await extrealMultiplayClient.ConnectAsync(connectionConfig);
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:19 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +// Join a group
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:20 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +SpawnObjectメソッドを使ってレイヤー以外のオブジェクトをスポーンします。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:21 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +### グループへの入退室を行う
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:21 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +同期されるオブジェクトにアタッチされたMultiplayPlayerInputのValuesの値を同期しています。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:21 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +同期されたValuesはSetValuesメソッドを使ってローカルオブジェクトに適用します。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:22 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +Move以外に他の入力情報を同期したい場合、MultiplayPlayerInputとMultiplayPlayerInputValuesを継承したクラスを作成し、Valuesにセットするようにします。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:23 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +#### 同期する入力情報を拡張する方法
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:23 UTC, mahaweilu commented on docs/integration/multiplay.common.md
> +例えば、Jumpという入力情報を同期したい場合、以下を参考にしてください。
ファイル名と構成(usageの流れ)を変え、変更点も多くてcommitだけで読みくいため、お手数ですがmessagingに関する指摘対応は以下から、multiplay.messaging.mdからご確認お願いします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/files

2023-12-22 08:24 UTC, mahaweilu commented on docs/intro.md
> +  - [Chat using WebRTC](./integration/chat.webrtc.md)
対応しました。[04c5531](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/04c55311eb61bc9427e35433afce5cebd084fd10)

2023-12-22 08:24 UTC, mahaweilu commented on docs/intro.md
> +  - [Chat using WebRTC](./integration/chat.webrtc.md)
[04c5531](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/04c55311eb61bc9427e35433afce5cebd084fd10)

2023-12-22 08:26 UTC, mahaweilu commented on docs/release/1.1.0.md
> +
lintによる自動フォーマットの変更のでした。lint削除と一緒に対応しました。

2023-12-22 08:28 UTC, mahaweilu commented on docs/release/unreleased.md
> +- PeerConnectionのCreate/Closeでエラーが発生しても処理を継続するように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/9))
対応しました。[e7b931c](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/e7b931cf104402bea288c89a11dde9c19d0239e9)

2023-12-22 08:28 UTC, mahaweilu commented on docs/release/unreleased.md
> +- [@extreal-dev/extreal.integration.messaging.redis](https://www.npmjs.com/package/@extreal-dev/extreal.integration.messaging.redis) 1.0.0-Next.1
[e7b931c](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/e7b931cf104402bea288c89a11dde9c19d0239e9)

2023-12-22 08:28 UTC, mahaweilu commented on docs/release/unreleased.md
> +2024-01-30
対応しました。[e7b931c](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/e7b931cf104402bea288c89a11dde9c19d0239e9)

2024-01-16 08:43 UTC, kiyohome requested changes

2024-01-16 08:43 UTC, kiyohome commented on docs/release/unreleased.md
> +- マルチプレイの方式をRedisのPub/SubとP2Pで選択できるように変更しました。([Doc](../sample-app/intro.md), [PR](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/11))
ここも変わってますよね。

2024-01-16 08:43 UTC, kiyohome commented on docs/sample-app/architecture.md
> +マルチプレイメッセージングサーバを通してアプリケーション間でデータをやりとりします。
既存の文に合わせて置き換えをしたように見えます。
Holidayの状態に合わせて見直して欲しいです。

2024-01-16 08:43 UTC, kiyohome commented on docs/sample-app/intro.md
> +HolidayではボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
「Holidayではボイスチャットは」
「は」が続いています。

2024-01-16 08:43 UTC, kiyohome commented on docs/sample-app/requirements.md
> +    - 1グループ100人
マルチプレイはグループですか？
テキストチャットは100人ですか？

2024-01-16 08:43 UTC, kiyohome commented on docs/sample-app/requirements.md
> +  - マルチプレイ、テキスト（Redisを使用したメッセージング）
Redisを使用したメッセージングとありますが、メッセージングだけではダメですか？
システムの構成図にメッセージングと書いてないですか？

2024-01-16 08:43 UTC, kiyohome commented on docs/sample-app/test-planning.md
> +- マルチプレイ、テキストチャット
テキストチャットは現状のHolidayの実装と合っていますか？
テキストチャットはグループ内のみかと思ってました。

2024-01-23 02:40 UTC, mahaweilu commented on docs/integration/messaging.md
> +## What for?
memo：
- 何のためにこの機能が提供されているのか？
  - メッセージングの実現を変更できるように(？)

2024-01-23 02:45 UTC, mahaweilu commented on docs/integration/messaging.md
> +グループでメッセージのやり取りをする機能を提供します。
memo：
- 具体例：「マルチプレイやテキストチャットなど、メッセージを複数人でやりとりしたい場合が多いので、グループでメッセージをやり取りできる機能を提供する」

2024-01-23 02:47 UTC, mahaweilu commented on docs/integration/messaging.md
> +Extrealではこの機能を提供するものを[メッセージングクライアント](https://github.com/extreal-dev/Extreal.Integration.Messaging.git)と呼ぶことにします。
memo：
- なぜ「メッセージングクライアント」と呼ぶのでしょうか？
  - 主にMessagingClient.csの提供だと考え....
  -  「メッセージング」にする

2024-01-23 02:51 UTC, mahaweilu commented on docs/integration/messaging.md
> +メッセージングクライアントを利用してメッセージングの実現方法を変更できます。
memo：
- 「メッセージングの実現方法」とは何のことでしょうか？
  - redisかlivekitかなど通信側の実装
- なぜこの変更が必要なのか 
  -  具体例「redisかlivekitなどから利用者自身が選択できるようにして便利」

2024-01-23 02:53 UTC, mahaweilu commented on docs/integration/messaging.md
> +## Specification
memo：
- Redisを使えることは仕様に書かないでしょうか
  - specificationの冒険に追加
  - native, webgl対応の分も追加

2024-01-23 02:54 UTC, mahaweilu commented on docs/integration/messaging.md
> +- グループを作成できます。
memo：
 - まとめる

2024-01-23 02:58 UTC, mahaweilu commented on docs/integration/messaging.md
> +- メッセージを扱うタイミングを制御（キューイング）できます。
memo：
- この機能を設けている説明を追記して、どのような場合に使うことを想定しているのか
 - 使用例を追加
   - マルチプレイを例として受送信の数が多い場合にキュイして通信負荷を減らす？

2024-01-23 03:01 UTC, mahaweilu commented on docs/integration/messaging.md
> +MessagingClientを実装したメッセージングクライアントの実現が必要です。
memo：
- 「MessagingClientを実装したメッセージングクライアント」とは？
 - 使用例を追加
   - マルチプレイを例として受送信の数が多い場合にキュイして通信負荷を減らす？

2024-01-23 03:05 UTC, mahaweilu commented on docs/integration/messaging.md
> +以下にRedisを使用したメッセージングクライアントの実現の例を示します。
memo：
- 唐突なため
  - MessagingClientクラスを実現したRedisMessaingClientのようなものを考え、唐突とは？

2024-01-23 03:07 UTC, mahaweilu commented on docs/integration/messaging.md
> +#### メッセージングサーバ
memo：
- 「メッセージングサーバ」とは何でしょうか？説明なく一般的でない用語が出てきてない
  -　「メッセージングサーバ」の定義をこの見出しの冒険に追加

2024-01-23 03:14 UTC, mahaweilu commented on docs/integration/messaging.md
> +サーバ・クライアント間はSocket.IOで接続し、Pub/SubはRedisのアダプターで実現しています。
memo：
- 説明順が練られていない、唐突
  -　説明順：「httpサーバを立てる --> サーバ・クライアント通信はsocket.io --> グループでのやり取りはsocket.io内部でredis pub/subで実現」を追加

2024-01-23 03:15 UTC, mahaweilu commented on docs/integration/messaging.md
> +Providerを使ってRedisのメッセージングクライアントを作成します。
memo：
- 具体的なクラス名
  - NativeRedisMessagingClient.csとWebGLRedisMessagingClient.csのクラスを明記する

2024-01-23 03:18 UTC, mahaweilu commented on docs/integration/messaging.md
> +QueuingMessagingClientを使用したい場合はこれも初期化します。
memo：
- QueuingMessagingClientの初期化は、唐突。MessagingClientのラッパークラスとして作ってことを伝え
  - Usageの最初のところに書く
    -  MessagingClientのラッパークラスとして作ってるってことも追加

2024-01-23 03:19 UTC, mahaweilu commented on docs/integration/messaging.md
> +グループを作成するためにはCreateGroupAsyncを使います。
memo：
-送受信の機能をMessagingClientが提供するとことを伝えてあげる
  - この文の前にに書く

2024-01-23 03:20 UTC, mahaweilu commented on docs/integration/messaging.md
> +var groupConfig = new GroupConfig("groupName", maxCapacity);
memo：
- 実装している機能や注意点などを伝えてますか？grougNameは重複しても大丈夫ですか？maxCapacityは毎回指定しないとダメですか？
  - grougName、maxCapacityの注意点を追記

2024-01-23 03:22 UTC, mahaweilu commented on docs/integration/messaging.md
> +存在するグループ一覧を取得するためにはListGroupsAsyncを使います。
memo: 削除

2024-01-23 03:23 UTC, mahaweilu commented on docs/integration/messaging.md
> +グループを削除するためにはDeleteGroupAsyncを使います。
memo：
- 利用シーンの説明を加えた方がいい
  - delete groupを削除したので対応不要

2024-01-23 03:24 UTC, mahaweilu commented on docs/integration/messaging.md
> +var connectionConfig = new MessagingJoiningConfig("groupName");
memo：
- このgroupNameはどこから取得するんですか？
  - 利用者自身が設定するって内容を追加

2024-01-23 03:24 UTC, mahaweilu commented on docs/integration/messaging.md
> +参加しているグループに送信するためにはSendMessageAsyncを使います。
memo：
- 「グループ」に修正

2024-01-23 03:25 UTC, mahaweilu commented on docs/integration/messaging.md
> +参加しているグループに送信するためにはSendMessageAsyncを使います。
memo：
- 「参加しているグループにメッセージを送信するためには」に修正

2024-01-23 03:25 UTC, mahaweilu commented on docs/integration/messaging.md
> +送信したい相手があれば対象を指定してメッセージを送信できます。
memo：
- 指摘通り修正

2024-01-23 03:30 UTC, mahaweilu commented on docs/integration/messaging.md
> +送信したい相手があれば対象を指定してメッセージを送信できます。
memo：
- 場合に分けた方が分かりやすい
  - 分ける
-   グループの特定参加者はどうやって取得しますか？
  - サーバ側Redisに参加者IDを入れているためそこから取得

2024-01-23 03:31 UTC, mahaweilu commented on docs/integration/messaging.md
> +グループから受信するためにはOnMessageReceivedイベント通知を使います。
memo：
- 何を受信するのか抜けてます。
  - 「グループからメッセージを受信するためには」に修正
-  グループ内の参加者でメッセージをやり取りする前提を、どこかに書いておけば、色々な箇所に書かなくてもよい
  - Usageの冒頭に書く

2024-01-23 03:34 UTC, mahaweilu commented on docs/integration/messaging.md
> +### キューイングを行う
memo：
- 何を受信するのか抜けてます。
  - 「仕様：グループに参加する」 --> 「Usage：グループへの参加を行う」のように修正

2024-01-23 03:39 UTC, mahaweilu commented on docs/integration/messaging.md
> +QueuingMessagingClientを使用することでメッセージをキューイングできます。
memo：
- キューイングされるのは送信？受信？
  - 両方
-  この章は全体的にどちらの話しをしているのか分からなかったです。
  - 送信のキューか受信のキューを分けるように、説明を追記
    - 例：「送信メッセージをキューイングする」見出し追加する

2024-01-23 03:39 UTC, mahaweilu commented on docs/integration/messaging.md
> +QueuingMessagingClientでは、MessagingClientのOnMessageReceivedのイベント通知に受信したメッセージをキューに追加しています。
memo：
- 指摘通り修正

2024-01-23 03:39 UTC, mahaweilu commented on docs/integration/messaging.md
> +キューから受信したメッセージをハンドリングします。
memo：
- 指摘通り修正

2024-01-23 03:39 UTC, mahaweilu commented on docs/integration/messaging.md
> +while (queuingMessagingClient.ResponseQueueCount() > 0)
memo：
- 指摘通り修正

2024-01-23 03:44 UTC, mahaweilu commented on docs/integration/messaging.md
> +  - パラメータ：切断する理由
memo：
- 「切断する理由」とは
  - グループから抜けた時に抜けた理由が「正常か、ネットワーク切断、最大人数となったなどの文字列」 
  - ↑のような理由の例を追加する

2024-01-23 03:45 UTC, mahaweilu commented on docs/integration/messaging.md
> +  - タイミング：参加承認が拒否された直後
memo：
- 「参加承認」とありますが、これは何でしょうか？
  - 最大人数となったときの話

2024-01-23 03:45 UTC, mahaweilu commented on docs/integration/messaging.md
> +  - パラメータ：接続したユーザID
memo：
- 「参加/接続、抜ける/切断」に統一する

2024-01-23 03:46 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +Extrealではプレイヤーが集まってマルチプレイを行うセッションをグループと呼ぶことにします。
memo：
- 指摘通りに修正

2024-01-23 03:46 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +このライブラリではメッセージングを使ってグループでマルチプレイできるようにします。
memo：
- 指摘通りに修正

2024-01-23 03:46 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +メッセージングを使ったスケールアウトしやすい構成をマルチプレイに活用することで、低コストかつ大規模なマルチプレイヤを実現できます。
memo：
- 指摘通りに修正

2024-01-23 03:47 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +### グループへの入退室を行う
memo：
- 指摘通りに修正

2024-01-23 03:48 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +var messagingJoiningConfig = new MessagingJoiningConfig("groupName");
memo：
- Usageの冒険にMessagingのjoin/leaveの基本的な仕様を参照している。と追記する

2024-01-23 03:48 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +### グループでマルチプレイを行う
memo：
- 指摘通り対応する

2024-01-23 03:49 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +### グループでメッセージの受送信を行う
memo：
- 指摘通り対応する

2024-01-23 03:50 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +参加しているグループに送信するためにはSendMessageを使います。
memo：
- Messaging側と同じように「メッセージ」を送信するに内容を追加

2024-01-23 03:50 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +送信したい相手があれば対象を指定してメッセージを送信できます。
memo：
- Messaging側と同じようにを対応

2024-01-23 03:51 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +デフォルトではMoveの動きのみ同期しています。
memo：
- 「Moveの動き」とは？
  - プレイヤーの動きを同期するため、動きの中で、Moveというのがあるイメージでした

2024-01-23 03:52 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +Moveの動き以外に他の動きを同期したい場合、PlayerInputとPlayerInputValuesを継承したクラスを作成してValuesにセットするようにします。
memo：
- 「ように」が要らないなど、全体にシンプルな言い回しに見直す

2024-01-23 03:54 UTC, mahaweilu commented on docs/release/1.2.0.md
> +  - アセットの暗号化と復号機能を使う場合はAssembly Definitionに`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`を追加してください。
memo：
- 色々試してこの行だけmainブランチに戻せなかった。よくわからず

2024-01-23 03:54 UTC, mahaweilu commented on docs/release/unreleased.md
> +- マルチプレイで使用する共通機能を追加しました。([Doc](../integration/multiplay.messaging.md))
memo：
- 指摘通り対応

2024-01-23 03:58 UTC, mahaweilu commented on docs/release/unreleased.md
> +- グループのメッセージ送受信で使用する共通機能を追加しました。([Doc](../integration/messaging.md))
memo：
-これも共通機能ではないですよね？
 - 見直す
- 「グループのメッセージ送受信で使用する」という表現も分かりにくい
 -  「メッセージング機能」に修正する

2024-01-23 03:59 UTC, mahaweilu commented on docs/release/unreleased.md
> +- マルチプレイの方式をRedisのPub/SubとP2Pで選択できるように変更しました。([Doc](../sample-app/intro.md), [PR](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/11))
memo：
- 新Holidayの現状にあわせて修正

2024-01-23 03:59 UTC, mahaweilu commented on docs/sample-app/architecture.md
> +マルチプレイメッセージングサーバを通してアプリケーション間でデータをやりとりします。
memo：
- 新Holidayの現状にあわせて修正

2024-01-23 04:00 UTC, mahaweilu commented on docs/sample-app/intro.md
> +HolidayではボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
memo：
- 指摘通り対応

2024-01-23 04:02 UTC, mahaweilu commented on docs/sample-app/requirements.md
> +    - 1グループ100人
memo：
- マルチプレイはグループですか？
  - Holidayではルームと呼ぶたたルームにした方がよいですか？Extrealのモジュールでは全部グループと呼ぶことにしています。
-  テキストチャットは100人ですか？
  -    マルチプレイと同じく100です

2024-01-23 04:04 UTC, mahaweilu commented on docs/sample-app/requirements.md
> +  - マルチプレイ、テキスト（Redisを使用したメッセージング）
memo：
- Redisを使用したメッセージングとありますが、メッセージングだけではダメですか？
  - メッセージングに修正します

2024-01-23 04:07 UTC, mahaweilu commented on docs/sample-app/test-planning.md
> +- マルチプレイ、テキストチャット
memo：
- テキストチャットは現状のHolidayの実装と合っていますか？
  - あっている
- テキストチャットはグループ内のみかと思ってました。
  - マルチプレイはVirtualSpace、Image、Videoのルームで行う。チャットはグループ選択画面で選択したグループで行う

2024-01-23 04:07 UTC, mahaweilu commented on docs/integration/messaging.md
> +Extrealではデフォルトで以下のメッセージンの実現方法を提供しています。
memo：
- 指摘通り対応

2024-01-23 04:08 UTC, mahaweilu commented on docs/integration/messaging.md
> +### メッセージングクライアント
memo：
- 指摘通り対応

2024-01-23 04:08 UTC, mahaweilu commented on docs/integration/messaging.md
> +### Redisを使用したメッセージングクライアントの実現
memo：
- 指摘通り対応

2024-01-23 04:09 UTC, mahaweilu commented on docs/integration/messaging.md
> +    RedisMessagingClientProvider --> RedisMessagingClient
memo：
- 他の関連も確認し依存へ修正

2024-01-23 04:09 UTC, mahaweilu commented on docs/integration/messaging.md
> +- [Extreal.Integration.Messaging](../integration/messaging.md)
memo：
- 指摘通り対応

2024-01-23 04:09 UTC, mahaweilu commented on docs/integration/messaging.md
> +[README](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/tree/main/RedisServer~)を参照してメッセージンサーバを準備してください。
memo：
- 指摘通り対応

2024-01-23 04:09 UTC, mahaweilu commented on docs/integration/messaging.md
> +var redisMessagingConfig = new RedisMessagingConfig("url", socketIOOptions);
memo：
- 指摘通り対応

2024-01-23 04:10 UTC, mahaweilu commented on docs/integration/messaging.md
> +var connectionConfig = new MessagingJoiningConfig("groupName");
memo：
- 指摘通り対応

2024-01-23 04:10 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +このモジュールは[Messaging](messaging.md)を使ってMultiplayを実現しています。
memo：
- 指摘通りに修正

2024-01-23 04:57 UTC, mahaweilu commented on docs/integration/messaging.md
> +## What for?
FB: メッセージング機能の必要性：例えばchat multiplayでよくメッセージのやり取りがあり。＜ー利用者がの実現をしたい場合、この機能が使える。共通するメッセージング部分を抽出する。変更できるのが断りではない
張：ソース目線で考えていた。他の人に読んでもらったり
読み手目線：なんでこの機能が使いたいと思う

2024-01-23 05:06 UTC, mahaweilu commented on docs/integration/messaging.md
> +メッセージングクライアントを利用してメッセージングの実現方法を変更できます。
FB：前提、ミードウェア

2024-01-23 05:17 UTC, mahaweilu commented on docs/integration/messaging.md
> +- グループを作成できます。
FB：想定してる使い方（エラーが出る？）、利用シーン、ストーリー性、maxCapacity, groupName、

2024-01-23 05:20 UTC, mahaweilu commented on docs/integration/messaging.md
> +- メッセージを扱うタイミングを制御（キューイング）できます。
FB：memoでも丁寧に

2024-01-23 05:30 UTC, mahaweilu commented on docs/integration/messaging.md
> +MessagingClientを実装したメッセージングクライアントの実現が必要です。
FB：設定方法、middlewareの話で、設定ではない

2024-01-23 06:41 UTC, mahaweilu commented on docs/integration/messaging.md
> +サーバ・クライアント間はSocket.IOで接続し、Pub/SubはRedisのアダプターで実現しています。
FB: そもそもメッセージングサーバの役割

2024-01-23 06:47 UTC, mahaweilu commented on docs/integration/messaging.md
> +QueuingMessagingClientを使用したい場合はこれも初期化します。
FB:Usageの冒頭に移動

2024-01-23 06:52 UTC, mahaweilu commented on docs/integration/messaging.md
> +QueuingMessagingClientを使用することでメッセージをキューイングできます。
FB：送受信のキュイイングの目的

2024-01-23 07:00 UTC, mahaweilu commented on docs/sample-app/requirements.md
> +    - 1グループ100人
混じっているのでややこしくて、わかりやすく伝えないといけない

2024-02-05 07:57 UTC, mahaweilu commented on docs/integration/messaging.md
> +Extrealではデフォルトで以下のメッセージンの実現方法を提供しています。
他の箇所も確認して修正しました。
[18545c7](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/18545c743d89c8e3ebee4abf3debd09b0d75aeb7)

2024-02-05 07:59 UTC, mahaweilu commented on docs/integration/messaging.md
> +Extrealではこの機能を提供するものを[メッセージングクライアント](https://github.com/extreal-dev/Extreal.Integration.Messaging.git)と呼ぶことにします。
メッセージングという表現に修正しました。
[18545c7](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/18545c743d89c8e3ebee4abf3debd09b0d75aeb7)

2024-02-05 08:05 UTC, mahaweilu commented on docs/integration/messaging.md
> +### メッセージングクライアント
他の箇所も確認して修正しました。
[18545c7](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/18545c743d89c8e3ebee4abf3debd09b0d75aeb7)

2024-02-05 08:58 UTC, mahaweilu commented on docs/integration/messaging.md
> +    RedisMessagingClientProvider --> RedisMessagingClient
messaging, messaging.redis, messaging.multiplayで関連するところを確認し修正しました。
[e278b97](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/e278b97ebfd4ed1ef726bf2522f02479adc1af81)

2024-02-05 09:08 UTC, mahaweilu commented on docs/integration/messaging.md
> +- [Extreal.Integration.Messaging](../integration/messaging.md)
削除して対応しました。
[f6a9309](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/f6a930973633ef0bd7ec728685eabc82e205dc4c)

2024-02-05 09:25 UTC, mahaweilu commented on docs/integration/messaging.md
> +[README](https://github.com/extreal-dev/Extreal.Integration.Messaging.Redis/tree/main/RedisServer~)を参照してメッセージンサーバを準備してください。
修正しました。
[f3ecbb9](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/f3ecbb92d033ef737fbff0494badea3acd541551)

2024-02-06 06:48 UTC, mahaweilu commented on docs/integration/messaging.md
> +Providerを使ってRedisのメッセージングクライアントを作成します。
C#とJS、両方修正しました。
[6a059ea](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/6a059eaf983de7460a529124d8ff023ae5276d0f)

2024-02-06 06:58 UTC, mahaweilu commented on docs/integration/messaging.md
> +var redisMessagingConfig = new RedisMessagingConfig("url", socketIOOptions);
ローカル変数命名にredisを付けないように修正しました。
[4080d61](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/4080d6114e55e8288808cdf9d2a96f88d2c5e975)

2024-02-09 09:49 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +## What for?
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/fd130663b4af380d2b182c27054128b1b4733b03

2024-02-09 09:49 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +グループでメッセージのやり取りをする機能を提供します。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/fd130663b4af380d2b182c27054128b1b4733b03

2024-02-09 09:49 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +メッセージングクライアントを利用してメッセージングの実現方法を変更できます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/fd130663b4af380d2b182c27054128b1b4733b03

2024-02-09 09:51 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +- グループを作成できます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dec5319f29672b78ae801bfb5bc6a4d57c0469a4 https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 09:53 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +- メッセージを扱うタイミングを制御（キューイング）できます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dec5319f29672b78ae801bfb5bc6a4d57c0469a4

2024-02-09 09:53 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +## Specification
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dec5319f29672b78ae801bfb5bc6a4d57c0469a4

2024-02-09 09:54 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +MessagingClientを実装したメッセージングクライアントの実現が必要です。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf71256137e7729713148c8cc32cf0ba93250f0f

2024-02-09 09:55 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +以下にRedisを使用したメッセージングクライアントの実現の例を示します。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf71256137e7729713148c8cc32cf0ba93250f0f

2024-02-09 09:57 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +#### メッセージングサーバ
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/76219a99bb5bc766eeeaed50c023c8b97f597a79

2024-02-09 09:57 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +サーバ・クライアント間はSocket.IOで接続し、Pub/SubはRedisのアダプターで実現しています。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/76219a99bb5bc766eeeaed50c023c8b97f597a79

2024-02-09 10:00 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +QueuingMessagingClientを使用したい場合はこれも初期化します。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/76219a99bb5bc766eeeaed50c023c8b97f597a79 https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/aa1ef8106d8ff9ecf82cfd61ed0f22dce0a6a2a8

2024-02-09 10:01 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +グループを作成するためにはCreateGroupAsyncを使います。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:01 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +var groupConfig = new GroupConfig("groupName", maxCapacity);
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:02 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +存在するグループ一覧を取得するためにはListGroupsAsyncを使います。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:02 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +グループを削除するためにはDeleteGroupAsyncを使います。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:03 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +var connectionConfig = new MessagingJoiningConfig("groupName");
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:03 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +var connectionConfig = new MessagingJoiningConfig("groupName");
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:03 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +参加しているグループに送信するためにはSendMessageAsyncを使います。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:05 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +参加しているグループに送信するためにはSendMessageAsyncを使います。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:05 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +送信したい相手があれば対象を指定してメッセージを送信できます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:06 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +送信したい相手があれば対象を指定してメッセージを送信できます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:06 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +グループから受信するためにはOnMessageReceivedイベント通知を使います。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/45cbe27bdc20265758e6344347cc1cfab6e615c0

2024-02-09 10:07 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +### キューイングを行う
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dec5319f29672b78ae801bfb5bc6a4d57c0469a4 https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/aa1ef8106d8ff9ecf82cfd61ed0f22dce0a6a2a8

2024-02-09 10:07 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +QueuingMessagingClientでは、MessagingClientのOnMessageReceivedのイベント通知に受信したメッセージをキューに追加しています。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/aa1ef8106d8ff9ecf82cfd61ed0f22dce0a6a2a8

2024-02-09 10:08 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +QueuingMessagingClientを使用することでメッセージをキューイングできます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/aa1ef8106d8ff9ecf82cfd61ed0f22dce0a6a2a8

2024-02-09 10:08 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +キューから受信したメッセージをハンドリングします。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/aa1ef8106d8ff9ecf82cfd61ed0f22dce0a6a2a8

2024-02-09 10:09 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +while (queuingMessagingClient.ResponseQueueCount() > 0)
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/aa1ef8106d8ff9ecf82cfd61ed0f22dce0a6a2a8

2024-02-09 10:14 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +  - パラメータ：接続したユーザID
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/d558b4600c574d94d70e67a1456a1e19b648f523 https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/a2786f7a8c6d17a272fb1529fc52d43793cf9d98

2024-02-09 10:15 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +Extrealではプレイヤーが集まってマルチプレイを行うセッションをグループと呼ぶことにします。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/a77b0b0d9c01246261bbf70ba110de0c162e7513

2024-02-09 10:15 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +このライブラリではメッセージングを使ってグループでマルチプレイできるようにします。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/a77b0b0d9c01246261bbf70ba110de0c162e7513

2024-02-09 10:16 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +メッセージングを使ったスケールアウトしやすい構成をマルチプレイに活用することで、低コストかつ大規模なマルチプレイヤを実現できます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/a77b0b0d9c01246261bbf70ba110de0c162e7513

2024-02-09 10:16 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +このモジュールは[Messaging](messaging.md)を使ってMultiplayを実現しています。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/ab4bc4e257a7b95a8d06b4ef32c9301757ff0bbf

2024-02-09 10:19 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +### グループへの入退室を行う
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/4eb44533a0ba78ed57c6d2f2a495f546ffe0a52d

2024-02-09 10:21 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +var messagingJoiningConfig = new MessagingJoiningConfig("groupName");
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/4eb44533a0ba78ed57c6d2f2a495f546ffe0a52d

2024-02-09 10:22 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +### グループでマルチプレイを行う
見出しの構成を見直しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/ab4bc4e257a7b95a8d06b4ef32c9301757ff0bbf https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/4eb44533a0ba78ed57c6d2f2a495f546ffe0a52d

2024-02-09 10:23 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +### グループでメッセージの受送信を行う
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/a4ea36778d80d0e565aeab6e9a8d691f2d859921

2024-02-09 10:23 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +参加しているグループに送信するためにはSendMessageを使います。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/a4ea36778d80d0e565aeab6e9a8d691f2d859921

2024-02-09 10:24 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +送信したい相手があれば対象を指定してメッセージを送信できます。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/a4ea36778d80d0e565aeab6e9a8d691f2d859921

2024-02-09 10:24 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +デフォルトではMoveの動きのみ同期しています。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/b9ba5e7e49eca0730e98dd91a63b6d62b6147070

2024-02-09 10:25 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +Moveの動き以外に他の動きを同期したい場合、PlayerInputとPlayerInputValuesを継承したクラスを作成してValuesにセットするようにします。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/b9ba5e7e49eca0730e98dd91a63b6d62b6147070

2024-02-09 10:25 UTC, sus-taguchi-t commented on docs/release/1.2.0.md
> +  - アセットの暗号化と復号機能を使う場合はAssembly Definitionに`Extreal.Integration.AssetWorkflow.Addressables.Custom.ResourceProviders`を追加してください。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/034a5e3da94b78ef035e430663c278091bff343a

2024-02-09 10:26 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- マルチプレイで使用する共通機能を追加しました。([Doc](../integration/multiplay.messaging.md))
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/f9281d5f0d0b5723f831a46eba2511bdae5d57c1

2024-02-09 10:26 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- グループのメッセージ送受信で使用する共通機能を追加しました。([Doc](../integration/messaging.md))
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/f9281d5f0d0b5723f831a46eba2511bdae5d57c1

2024-02-09 10:27 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- マルチプレイの方式をRedisのPub/SubとP2Pで選択できるように変更しました。([Doc](../sample-app/intro.md), [PR](https://github.com/extreal-dev/Extreal.SampleApp.Holiday/pull/11))
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/f9281d5f0d0b5723f831a46eba2511bdae5d57c1

2024-02-09 10:27 UTC, sus-taguchi-t commented on docs/sample-app/architecture.md
> +マルチプレイメッセージングサーバを通してアプリケーション間でデータをやりとりします。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/84def10cc5d9593664ec01bf865d2f4241edb329

2024-02-09 10:28 UTC, sus-taguchi-t commented on docs/sample-app/intro.md
> +HolidayではボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/d693c27de7ef44cb9b037bf570249d74a88c3e65

2024-02-09 10:28 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +    - 1グループ100人
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/369e415ebe99d20127fb43a1dbd18ce11bbc6832

2024-02-09 10:29 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - マルチプレイ、テキスト（Redisを使用したメッセージング）
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/369e415ebe99d20127fb43a1dbd18ce11bbc6832
/

2024-02-09 10:30 UTC, sus-taguchi-t commented on docs/sample-app/test-planning.md
> +- マルチプレイ、テキストチャット
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/c616268d3dba91323f96dba8b7fa1fbe775b5168

2024-02-09 10:33 UTC, sus-taguchi-t commented on docs/integration/messaging.md
> +## Architecture
コードの変更に合わせて修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7792d501aa9624e137f7fe56cb0d9eaa4d12fa1a

2024-02-09 10:33 UTC, sus-taguchi-t commented on docs/integration/multiplay.messaging.md
> +## Architecture
コードの変更に合わせて修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/be23c1b0d895e8a558fcccd202ca33828cc3aff4

2024-02-09 10:35 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- マルチプレイで使用する共通機能を追加しました。([Doc](../integration/multiplay.common.md))
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/f9281d5f0d0b5723f831a46eba2511bdae5d57c1

2024-02-20 10:01 UTC, kiyohome requested changes

2024-02-20 10:01 UTC, kiyohome commented on docs/sample-app/intro.md
> +テキストチャットは[Messaging](../integration/messaging.md)、ボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
あと、ここの最後にinfoで「P2P(Peer to Peer)を採用してマルチプレイ/テキストチャット/ボイスチャットを実現したHolidayは次のリポジトリを参照してください。
リポジトリURL」を入れといてください。

2024-02-26 01:46 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +バーチャル空間等ではマルチプレイやテキストチャットなど、メッセージをグループでやりとりしたい場合が多くあります。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dcfe6e63e3affe67d2b0bfe0b048ed21419b59cc

2024-02-26 01:46 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +メッセージをグループでやりとりする際に使用するAPIは似通ったものになるため共通部分を提供します。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dcfe6e63e3affe67d2b0bfe0b048ed21419b59cc

2024-02-26 01:47 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +このモジュールを使うことでRedisやLiveKitなど通信側の実装をアプリ要件に合わせて自由に変更できるようになります。
Socket.IOにして修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dcfe6e63e3affe67d2b0bfe0b048ed21419b59cc

2024-02-26 01:47 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +Extrealではこのモジュールで提供する機能を[メッセージング](https://github.com/extreal-dev/Extreal.Integration.Messaging.git)と呼ぶことにします。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dcfe6e63e3affe67d2b0bfe0b048ed21419b59cc

2024-02-26 01:56 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +Extrealではデフォルトで以下のメッセージングの実現方法を提供しています。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/dcfe6e63e3affe67d2b0bfe0b048ed21419b59cc

2024-02-26 01:57 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +- Redisによるメッセージングができます。（Redis）
Socket.IOにして修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/1498c0fe688754d6ee7bc76d7529116bf28949b0

2024-02-26 01:58 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +アプリ要件に合わせてRedisやLiveKitなどのメッセージングの通信側の実装を準備します。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/18ef3e381d70fe074c8b868be47c2ec3d78bfefd

2024-02-26 01:59 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +グループでのメッセージングはSocket.IOの内部でRedisのPub/Subを使用することで実現しています。
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/13adbec5ebf52f9ab73c9c2f9455cd68940de017

2024-02-26 02:00 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +
追加しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/13adbec5ebf52f9ab73c9c2f9455cd68940de017

2024-02-26 02:12 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +現在存在するグループ一覧を取得するためにはListGroupsAsyncを使います。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:12 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +Nameを持ったGroupのリストが返るので、ここで取得したGroupのNameを使ってグループに参加します。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:13 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +取得したGroupのNameに含まれないグループ名を使用した場合は新たにグループが作成されます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:14 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +メッセージを送信するためにはSendMessageAsyncを使います。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:15 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +引数にクライアントIDを渡すことで送信先を指定することができます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:16 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +クライアントIDはJoinedClientsプロパティから取得できます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:34 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +受信したメッセージはOnMessageReceivedイベントから受け取れます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:35 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +var toClientId = messageClient.JoinedClients.First();
Firstに送信するケースは基本的にないため削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:36 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +グループから抜けるためにはLeaveAsyncを使います。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cf0d9801539bdb7e5a36e0e53cc9712a794e8fa6

2024-02-26 02:37 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +キューイングの機能はQueuingMessagingClientが提供します。
キューイング機能に修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/fa53f15a4d7171617c300e97977982a09ed93976

2024-02-26 02:39 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +このような設計は、スケールアウト（サーバの能力を拡張して処理能力を増やすこと）を難しくしています。
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/406ae1e46dba3f28692964db08e9c4f5f18bab89

2024-02-26 02:39 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +RedisのPub/Subのようなメッセージングを採用することで、複数のチャンネルをプロセス内で管理できる構造を実現し、分散処理が容易になります。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/406ae1e46dba3f28692964db08e9c4f5f18bab89

2024-02-26 02:40 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +このモジュールではプレイヤーが集まってマルチプレイを行うセッションをグループと呼ぶことにします。
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/406ae1e46dba3f28692964db08e9c4f5f18bab89

2024-02-26 02:40 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +// List groups
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9ca1c299db7db443056e3bbb38e159a4d41788ba

2024-02-26 02:41 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +グループに参加したらプレイヤーをスポーンしてマルチプレイを行います。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9ca1c299db7db443056e3bbb38e159a4d41788ba

2024-02-26 02:41 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +SpawnObjectメソッドを使ってプレイヤーをスポーンします。
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9ca1c299db7db443056e3bbb38e159a4d41788ba

2024-02-26 02:42 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +グループでマルチプレイをするにはグループに参加したりグループから抜けたりする必要がありますが、このモジュールではこれらの機能は[Messaging](./messaging.md)に委譲しています。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9ca1c299db7db443056e3bbb38e159a4d41788ba

2024-02-26 02:43 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +このモジュールではこれらの機能は次のようにして使用します。
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9ca1c299db7db443056e3bbb38e159a4d41788ba

2024-02-26 02:44 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +グループでマルチプレイをするにはグループに参加したりグループから抜けたりする必要がありますが、このモジュールではこれらの機能は[Messaging](./messaging.md)に委譲しています。
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9ca1c299db7db443056e3bbb38e159a4d41788ba

2024-02-26 02:44 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +リアクションの同期など、マルチプレイしているグループ内でメッセージを送受信したい場合がありますが、このモジュールではこの機能は[Messaging](./messaging.md)に委譲しています。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/4d502b1156b57cb66beff0b1f953a005410e1a55

2024-02-26 02:45 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +// Send message to a specified destination
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/4d502b1156b57cb66beff0b1f953a005410e1a55

2024-02-26 02:45 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +:::info
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7c3508ed0dda8ebb4689510d55a0541d51be79d8

2024-02-26 02:46 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +オブジェクトをスポーンさせると位置(Position)と回転(Rotation)は自動で同期されます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7c3508ed0dda8ebb4689510d55a0541d51be79d8

2024-02-26 02:46 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +マルチプレイする際にはアニメーションなど、オブジェクトの位置と回転以外の動きも同期したい場合が多くあります。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7c3508ed0dda8ebb4689510d55a0541d51be79d8

2024-02-26 02:47 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +このモジュールではアプリ使用者からの入力を同期することでこれを実現しています。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7c3508ed0dda8ebb4689510d55a0541d51be79d8

2024-02-26 02:48 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +アプリ使用者からの入力は一定時間ごとに同期されます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7c3508ed0dda8ebb4689510d55a0541d51be79d8

2024-02-26 02:49 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +入力が変わるごとに同期したい場合など、同期するタイミングを制御したい場合はCheckWhetherToSendDataメソッドを使用することで実現できます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/7c3508ed0dda8ebb4689510d55a0541d51be79d8

2024-02-26 03:05 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +[Messaging](messaging.md)を利用してイベント通知しています。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/9f05ecc0700194bc3a01ca87e0e5976a9480446a
不要な部分を追加してしまっていたため削除しました。
https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/c18012d4a1739bda251cc27a56d3191deeac0b32

2024-02-26 03:05 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- メッセージをグループでやりとりするベース機能を追加しました。([Doc](../integration/messaging.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Messaging/pull/1))
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/e040cae14178e63a34e1173f9cd7df32ffcf6505

2024-02-26 03:05 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +### Extreal.Integration.Messaging
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/e040cae14178e63a34e1173f9cd7df32ffcf6505

2024-02-26 03:07 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +### Extreal.Integration.Messaging
モジュール名がSocketIOになっていたため修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/750d9c6249b53f5bd5ae6ed2ca388ce7ba971990

2024-02-26 03:08 UTC, sus-yoshikane-t commented on docs/sample-app/intro.md
> +テキストチャットは[Messaging](../integration/messaging.md)、ボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/67453e993784289dab42a5554b2414b1919de0a6

2024-02-28 05:19 UTC, sus-yoshikane-t commented on docs/integration/multiplay.messaging.md
> +リアクションの同期など、マルチプレイしているグループ内でメッセージを送受信したい場合がありますが、このモジュールではこの機能は[Messaging](./messaging.md)に委譲しています。
修正しました。https://github.com/extreal-dev/Extreal.Guide/commit/4d502b1156b57cb66beff0b1f953a005410e1a55

2024-02-28 06:52 UTC, mahaweilu commented on docs/integration/messaging.md
> +クライアントIDはJoinedClientsプロパティから取得できます。
吉兼さんに連携していただいて、JoinedClientsは利用者側でOnClientJoinedから作成できると判明しました。

そのためJoinedClientsをライブラリから削除したのでガイドも修正しました。ライブラリ側のPRは
[1081711](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/108171195e368501aaee1a32db2b5d6ea25b234e)

2024-02-28 07:56 UTC, mahaweilu commented on docs/integration/multiplay.messaging.md
> +最後にアプリ使用者からの入力を同期した時から一定時間が経過したら自動でまた入力を同期するようになっています。
修正しました。
[5debec1](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/5debec1d9325869f88aefa5a06c4c9104c3dec02)
[9425033](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/942503366603f6b56bbe6d88a2a04aa096ff2e02)

2024-02-29 01:16 UTC, mahaweilu commented on docs/integration/messaging.md
> +  - パラメータ：切断する理由
修正しました。
[ffb75f1](https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/ffb75f1de0425be6a8b738edc548727813bd6841)

2024-02-29 08:29 UTC, kiyohome commented on docs/integration/messaging.md
> +グループでのメッセージングはSocket.IOの内部でRedisのPub/Subを使用することで実現しています。
「RedisのPub/Sub」を外したという意味でした。
元の文
```
実装としてはHTTPサーバを立てており、サーバ・クライアント間はSocket.IOで接続しています。
グループでのメッセージングはSocket.IOの内部でRedisのPub/Subを使用することで実現しています。
詳細は[Redis adapter](https://socket.io/docs/v4/redis-adapter/)および[Rooms](https://socket.io/docs/v4/rooms/)を参照してください。
```
こんな感じでどうでしょうか。
```
グループでのメッセージングはSocket.IOの[Rooms](https://socket.io/docs/v4/rooms/)を使用しています。
```

2024-02-29 08:47 UTC, kiyohome commented on docs/integration/messaging.md
> +Nameを持ったGroupのリストが返るので、ここで取得したGroupのNameを使ってグループに参加します。
「Nameを持ったGroupのリストが返るので、ここで取得したGroupのNameを使って」の実装例がどれか分かりませんでした。

2024-03-04 01:58 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +グループでのメッセージングはSocket.IOの内部でRedisのPub/Subを使用することで実現しています。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/bd0a2cf3055a4db86f7da3877bf0c1cdd4b7b4e7

2024-03-04 02:00 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +Nameを持ったGroupのリストが返るので、ここで取得したGroupのNameを使ってグループに参加します。
修正が漏れていたため修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/530c092cf8c6d01569eafdd1b08039e195c32655

2024-03-04 08:39 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +グループでのメッセージングはSocket.IOの内部でRedisのPub/Subを使用することで実現しています。
再度修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/3ebbbe5ac5186181d52def34922a1949f6a6a008

2024-03-04 08:40 UTC, sus-yoshikane-t commented on docs/integration/messaging.md
> +Nameを持ったGroupのリストが返るので、ここで取得したGroupのNameを使ってグループに参加します。
再度修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/56/commits/cfcebcaead6169c3b8271edb9ad8470fba0a3e0f

2024-03-04 08:53 UTC, kiyohome approved these changes

2024-03-04 09:15 UTC, sus-yoshikane-t approved these changes

2024-03-05 02:11 UTC, merged