PeerConnectionのCreate/Close時にエラーが起こった場合の注意点を追加
extreal-dev/Extreal.Guide pull request #57
Opened 2023-12-04 10:44 UTC by sasuke9410

﻿# 何の変更を加えましたか？
- Extreal.Integration.P2P.WebRTCが、[PeerConnectionのCreate/Closeでエラーが発生しても処理を継続するように変更](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/9)されるようになったため、ガイドに注意点を追記しました

# 何を確認しましたか?

- [x] 変更したページと影響がありそうなページをブラウザで確認しました
- [x] 日本語と英語のページが一致していることを確認しました
- [x] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2023-12-05 01:55 UTC, sus-taguchi-t requested changes

2023-12-05 01:55 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +Processing continues even if an error occurs during Create/Close of PeerConnection.
if an error occurs -> if errors occur

WebGL の方の記述も同様です。

2023-12-05 01:55 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
Relesase ページには記載しなくて良いのでしょうか？

2023-12-06 04:14 UTC, sasuke9410 commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +Processing continues even if an error occurs during Create/Close of PeerConnection.
Fixed 382485a2c9851522392421e1938ac49f17726a34

2023-12-12 00:22 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/integration/p2p.webrtc.md
> +Processing continues even if an error occurs during Create/Close of PeerConnection.
確認しました！

2023-12-12 00:27 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
最初なので `Unity version` や `Modules` といったその他の内容も書いておいた方が良いと思います。

2023-12-12 10:55 UTC, sasuke9410 commented on docs/integration/p2p.webrtc.md
Fixed 691c59c9b38cf08ceed250796690ceb9b64b1600

2023-12-14 04:57 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
確認しました！

2023-12-14 04:59 UTC, sus-taguchi-t requested changes

2023-12-14 04:59 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +#### Added
すみません今気づいたのですが、`Added` ではなく `Changed` ではないでしょうか？

2023-12-15 00:25 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +#### Added
確認しました！

2023-12-15 00:33 UTC, sus-taguchi-t requested changes

2023-12-15 00:33 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +sidebar_position: 1
こちらも今気づいてしまいました。すみません。
`release` 内のすべてのページのポジションをずらさないとビルドしたときに想定外の並び順になると思います。

2023-12-15 00:38 UTC, sus-taguchi-t requested changes

2023-12-15 00:38 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +# Unreleased
いつもこのガイドを main にマージする日付をここに書いています。
今回は書かなくて良いのでしょうか？

2023-12-15 00:38 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +## Changes
release ページには `Upgrade guide` という見出しもあると思いますが、書かなくて良いのでしょうか？

2023-12-15 03:02 UTC, sasuke9410 commented on docs/release/unreleased.md
> +sidebar_position: 1
ありがとうございます 再確認しました
Fixed 327a84f12294f05ed0bd0f46d9f5e6978859a06c

2023-12-15 03:27 UTC, sasuke9410 commented on docs/release/unreleased.md
> +# Unreleased
追記しました。
Fixed 4fc8ade2e80e56eada1f524207fdfd428a447eb3

2023-12-15 03:28 UTC, sasuke9410 commented on docs/release/unreleased.md
> +## Changes
今回は該当しない認識ですが、
フォーマットとして項目を作っておくという意味では必要だと思いました。
Fixed 4fc8ade2e80e56eada1f524207fdfd428a447eb3

2023-12-15 04:13 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +sidebar_position: 1
確認しました

2023-12-15 04:14 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +# Unreleased
確認しました

2023-12-15 04:14 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +## Changes
確認しました

2023-12-15 04:18 UTC, sus-taguchi-t requested changes

2023-12-15 04:18 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +後方互換に影響がある変更があるため、下記を確認して該当するアプリケーションは対応してください。
現時点では後方互換に影響がないと思っていたのですが、この 1 文は必要でしょうか？
また必要な場合は対処法まで記述しなければいけないと思うのですが書かなくて良いのでしょうか？

2023-12-15 07:23 UTC, sasuke9410 commented on docs/release/unreleased.md
> +後方互換に影響がある変更があるため、下記を確認して該当するアプリケーションは対応してください。
ありがとうございます。
>現時点では後方互換に影響がないと思っていたのですが、この 1 文は必要でしょうか？
ご指摘の通り、このPRでは後方互換に影響があるものは存在しません。
テンプレとして置いたつもりでしたが、誤解を招きそうなので削除しました。

Fixed 7e3adb7a104807a727d6cca58c6e9c723f83f675

2023-12-15 07:42 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +後方互換に影響がある変更があるため、下記を確認して該当するアプリケーションは対応してください。
確認しました！

2023-12-15 07:43 UTC, sus-taguchi-t approved these changes

2023-12-15 07:43 UTC, merged