SocketIDをイベントとして取得できるようになったことを追記
extreal-dev/Extreal.Guide pull request #58
Opened 2023-12-14 09:51 UTC by sasuke9410

﻿# 何の変更を加えましたか？
- Extreal.Integration.P2P.WebRTCが、[SocketIDをイベントとして取得できるようになった](https://github.com/extreal-dev/Extreal.Guide/pull/57)ため、ガイドに追記しました
# 何を確認しましたか?

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました
- [ ] 日本語と英語のページが一致していることを確認しました
- [ ] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2023-12-20 07:11 UTC, sus-taguchi-t requested changes

2023-12-20 07:11 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +  - タイミング：自分の接続直後または他のユーザが接続した直後
「自分の接続直後」も他のユーザと接続したから発火するのではないのでしょうか？

2023-12-20 07:11 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- P2P通信時にSocketIDをイベントとして取得できるように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Guide/pull/58))
PR のリンクは P2P.WebRTC の方の PR へのリンクではないでしょうか？

2023-12-20 07:11 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
> +- Changed so that SocketID can be obtained as an event during P2P communication. ([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Guide/pull/58))
during -> at

2023-12-21 11:39 UTC, sasuke9410 commented on docs/integration/p2p.webrtc.md
> +        +SocketId string
Fixed 664ca6b9865c7eb44e564f8db3d599c5bf36e20b

2023-12-21 11:43 UTC, sasuke9410 commented on docs/release/unreleased.md
> +- P2P通信時にSocketIDをイベントとして取得できるように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Guide/pull/58))
Fixed 43de34bb7675c9f0c1697340e31918f21c09c658

2023-12-21 11:44 UTC, sasuke9410 commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
> +- Changed so that SocketID can be obtained as an event during P2P communication. ([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Guide/pull/58))
Fixed e1d1b41e56a78f9fd51c806db0f71bb69958a787

2023-12-21 11:59 UTC, sasuke9410 commented on docs/integration/p2p.webrtc.md
> +  - タイミング：自分の接続直後または他のユーザが接続した直後
パターンを2つ考えています。
①他ユーザが先に接続しており、自分は後で入る
　→ 「自分の接続直後」に、他ユーザのSocketIDが飛んできます
②自分が先に接続しており、他ユーザが後で入る
　→ 「自分の接続直後」は飛ばず、「ほかのユーザが接続した直後」他ユーザのSocketIDが飛んできます
　
上記①②を一文にした結果修正箇所のようになっています。

2023-12-22 02:15 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +        +SocketId string
確認しました。

2023-12-22 02:26 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +  - タイミング：自分の接続直後または他のユーザが接続した直後
①のパターンも自分の接続直後に自分と他のユーザが接続したからイベントが発火するのではないでしょうか？

2023-12-22 02:26 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- P2P通信時にSocketIDをイベントとして取得できるように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Guide/pull/58))
確認しました。

2023-12-22 02:26 UTC, sus-taguchi-t commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
> +- Changed so that SocketID can be obtained as an event during P2P communication. ([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Guide/pull/58))
確認しました。

2024-01-09 04:40 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +  - タイミング：自分の接続直後または他のユーザが接続した直後
「他のユーザと接続した直後」に変更しました。https://github.com/extreal-dev/Extreal.Guide/pull/58/commits/e4494b191baf11bd1f50d77eeb23eb8c37335b46

2024-01-09 05:04 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +  - タイミング：自分の接続直後または他のユーザが接続した直後
確認しました！

2024-01-09 05:07 UTC, sus-taguchi-t approved these changes

2024-01-10 03:04 UTC, kiyohome requested changes

2024-01-10 03:04 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +  - パラメータ：自分のSocketID
質問です。他のガイドでも「自分」と表現してましたか？

2024-01-10 03:04 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +  - タイミング：他のユーザと接続した直後
説明をちゃんと書かないと伝わりにくいと思います。
P2Pなので、お互いに接続するので、お互いにこのイベントを受け取るということですか？
他のユーザーが接続した直後、でしょうか？
お互いに受け取るのか、どうか含めて伝えましょう。

2024-01-10 09:07 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +モジュールバージョンを更新してください。
最終行に改行がなかったところに改行が追加されていました。
mainブランチでは最終行の改行が
- 1.0.0と1.1.0：改行有
- 1.2.0とunreleased：改行無
となっているようなのですが、どちらにするのがよいでしょうか？

2024-01-10 10:29 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +  - パラメータ：自分のSocketID
同様の個所では「自分」と表現している個所はありませんでした。
[Chat.Vivoxのガイドに「ユーザー自身」という表現があった](https://extreal-dev.github.io/Extreal.Guide/integration/chat.vivox#chat-vivox-event)ため、「ユーザー自身」に修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/58/commits/396cdc2f6b775c9652051cb13d3dab8767e830b8

2024-01-10 10:30 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- P2P通信時にSocketIDをイベントとして取得できるように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10))
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/58/commits/51f5b98dfe9f1d100bd8ac76543ea5cf14e49877

2024-01-10 10:31 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +  - タイミング：他のユーザと接続した直後
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/58/commits/7ffb74a3315363d7d9b6fd17469c3693eedbf41d

2024-01-16 11:38 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +  - タイミング：他のユーザと接続した直後
「そのため新たに接続したユーザーは、既に接続しているすべてのユーザーに対してイベントを受け取ることになります。」
→
「そのため新たに接続したユーザーは、既に接続している**全て**の**ユーザー数のイベント**を受け取ります。」

2024-01-16 11:41 UTC, kiyohome requested changes

2024-01-16 11:41 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +  - パラメータ：ユーザー自身のSocketID
SocketID、というよりクライアントIDの方がよくないでしょうか？
変更する場合、ソースも合わせて見直しをお願いします。

2024-01-18 01:30 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +  - タイミング：他のユーザと接続した直後
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/58/commits/f8fcaf720297f9343899d03cd2565f0621541cd3

2024-01-18 01:31 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +  - パラメータ：ユーザー自身のSocketID
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/58/commits/fc9259f7a8ce58d3e3d32f727682daa04cb2b08f
ソース側も修正しました。
https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/7fa5d9db0877e62749a27bc4a3509357e5aafacd

2024-01-18 04:27 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +モジュールバージョンを更新してください。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/58/commits/ede687d4df1c5cac16c6e6e4e50a5d7ffbbffb77

2024-01-23 07:57 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +  - パラメータ：ユーザー自身のSocketID
ClientIDではなく、LocalClientIdにしている理由はありますか？

2024-01-23 08:24 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +  - パラメータ：ユーザー自身のSocketID
イベントで他人のクライアントIDが流れてくるものもあるため、明示した方がよいと考えLocalを付けていました。

しかし、このメソッドはprotectedであり、C#ドキュメントのみで開発者には伝わるため、ClientIdに修正しました。 https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/10/commits/d59558b7dfa712f1a4bba9b1646ebb491097990a

2024-01-23 09:07 UTC, kiyohome approved these changes

2024-01-23 09:08 UTC, kiyohome approved these changes

2024-01-23 09:09 UTC, merged