ボイスチャットの機能改善のガイド追記
extreal-dev/Extreal.Guide pull request #59
Opened 2023-12-14 10:47 UTC by sus-yoshikane-t

﻿# 何の変更を加えましたか？

- [x] Extreal.Integration.Chat.WebRTCのガイドにボイスチャットの機能改善部分を追記しました。(FB前)
- [ ] Extreal.Integration.Chat.WebRTCのガイドにFB内容を取り込みました。

# 何を確認しましたか?

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました
- [ ] 日本語と英語のページが一致していることを確認しました
- [ ] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2023-12-20 07:45 UTC, mahaweilu commented on docs/release/unreleased.md
> +- サンプルのClientControlシーンに存在していた不要なオブジェクトを削除しました。([Doc](../integration/chat.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8))
過去の1.1.0や1.2.0から見てわかると思いますが、機能面の変更や不具合修正の内容がここに入ります。なのでサンプルの修正に関する内容は不要かと思います。

2023-12-20 07:45 UTC, mahaweilu commented on docs/integration/chat.webrtc.md
> +発話音量の変化時に、IDと発話音量のペアをOnAudioLevelChangedイベントで受け取ることができます。
過去のガイドに似たような内容を参照して修正した方が良いと思います。（すでに参考して書いていればすみません）。例えば、以下のように「発話音量変化？のトリガーに処理追加することができます」みたいな表現です。
[VoiceChatClient.ts](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8/files#diff-09ea46168582e9cfee7875e722b3fd9762eaeb41ffe2a8c6419888153349830c)

2023-12-20 07:45 UTC, mahaweilu commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
> +
これは何ですか？なにかフォーマット機能を使っているかと思ったり...

既存のガイドにこのようなフォーマットではないなら、既存に一致したほうが良いと思います。

2023-12-20 07:45 UTC, mahaweilu commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
> +- Removed unnecessary objects existed in the sample ClientControl scene. ([Doc](../integration/chat.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8))
日本版と同じようにいらないと思います

2023-12-21 01:10 UTC, sus-taguchi-t requested changes

2023-12-21 06:44 UTC, sasuke9410 reviewed
完全に重複する指摘の場合は、指摘に👍つけてます

2023-12-22 06:14 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- サンプルのClientControlシーンに存在していた不要なオブジェクトを削除しました。([Doc](../integration/chat.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8))
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/3c555b44b16035b44eb20a986e54545162b352d9

2023-12-22 06:14 UTC, sus-yoshikane-t commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
> +- Removed unnecessary objects existed in the sample ClientControl scene. ([Doc](../integration/chat.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8))
削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/3c555b44b16035b44eb20a986e54545162b352d9

2023-12-22 06:15 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- ボイスチャットで他の人の音量を調節できる機能を追加しました。([Doc](../integration/chat.webrtc.md))
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/8eec017780401371391a229dd51d176efc8d5ea6

2023-12-22 06:16 UTC, sus-yoshikane-t commented on i18n/en/docusaurus-plugin-content-docs/current/release/unreleased.md
> +
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/05c9524bfa01d70c9ffc9ec6fe1d3f4e789079e3

2023-12-22 06:16 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/05c9524bfa01d70c9ffc9ec6fe1d3f4e789079e3

2023-12-28 09:09 UTC, sus-yoshikane-t commented on docs/integration/chat.webrtc.md
> +発話音量の変化時に、IDと発話音量のペアをOnAudioLevelChangedイベントで受け取ることができます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/603d581ac936c314f3e3754ec0799462c17da770

2023-12-28 09:09 UTC, sus-yoshikane-t commented on docs/integration/chat.webrtc.md
> +発話音量の変化時に、IDと発話音量のペアをOnAudioLevelChangedイベントで受け取ることができます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/603d581ac936c314f3e3754ec0799462c17da770

2024-02-02 06:53 UTC, sus-yoshikane-t commented on docs/integration/chat.webrtc.md
> +発話音量の変化時に、IDと発話音量のペアをOnAudioLevelChangedイベントで受け取ることができます。
変化した参加者の分だけ送るように変更になったため再度修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/1789755daacf864c55037dc666dfefa05cc01245

2024-02-02 07:05 UTC, sasuke9410 approved these changes

2024-02-07 04:40 UTC, sus-taguchi-t commented on docs/integration/chat.webrtc.md
> +発話音量の変化時に、IDと発話音量のペアをOnAudioLevelChangedイベントで受け取ることができます。
確認しました。

2024-02-07 04:41 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +
確認しました。

2024-02-07 04:41 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- ボイスチャットで他の人の音量を調節できる機能を追加しました。([Doc](../integration/chat.webrtc.md))
確認しました。

2024-02-07 04:41 UTC, sus-taguchi-t approved these changes

2024-02-07 09:56 UTC, mahaweilu approved these changes

2024-02-21 05:22 UTC, kiyohome requested changes

2024-02-21 05:22 UTC, kiyohome commented on docs/release/unreleased.md
> +- マイクが使用できない場合、ボイスチャットで聞くのみになるように変更しました。([Doc](../integration/chat.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8))
「ボイスチャットでマイクが使用できない場合はスピーカーのみ有効となるように変更しました。」とかでしょうか。

2024-02-21 05:30 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- マイクが使用できない場合、ボイスチャットで聞くのみになるように変更しました。([Doc](../integration/chat.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Chat.WebRTC/pull/8))
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/59/commits/88e2ea7d1563070ba284cf687be1eb8d6aa18548

2024-02-21 05:41 UTC, kiyohome approved these changes

2024-02-21 05:41 UTC, merged