トレースログ抑制のガイド追記
extreal-dev/Extreal.Guide pull request #60
Opened 2024-01-11 08:35 UTC by sus-yoshikane-t

﻿# 何の変更を加えましたか？
- addAction/addFunction/callbackで指定したターゲット名を使用して、特定のトレースログを抑制できる機能について追記しました。
  - [ライブラリのPR](https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/7)

# 何を確認しましたか?

- [x] 変更したページと影響がありそうなページをブラウザで確認しました
- [x] 日本語と英語のページが一致していることを確認しました
- [x] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2024-01-12 01:31 UTC, sus-taguchi-t requested changes

2024-01-12 01:31 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- 関数呼び出しとコールバック時のログ出力有効時に、指定した関数呼び出しとコールバックのログを抑制する機能を追加しました。([Doc](../integration/web.common.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/7))
「関数呼び出しとコールバック時のログ出力有効時に、」の部分は不要だと思います。

2024-01-12 01:31 UTC, sus-taguchi-t commented on docs/integration/web.common.md
> +        +suppressTraceLog(string) void
string -> name

2024-01-12 04:09 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- 関数呼び出しとコールバック時のログ出力有効時に、指定した関数呼び出しとコールバックのログを抑制する機能を追加しました。([Doc](../integration/web.common.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/7))
削除しました。
https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/bc6441abae625a73f2725f5b1c9794133ea77d6f

2024-01-12 04:09 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +        +suppressTraceLog(string) void
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/cf3c96674acf95eb91d365c40ceff7dfd3bde8e1

2024-01-12 04:35 UTC, sus-taguchi-t commented on docs/release/unreleased.md
> +- 関数呼び出しとコールバック時のログ出力有効時に、指定した関数呼び出しとコールバックのログを抑制する機能を追加しました。([Doc](../integration/web.common.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/7))
確認しました。

2024-01-12 04:35 UTC, sus-taguchi-t commented on docs/integration/web.common.md
> +        +suppressTraceLog(string) void
確認しました。

2024-01-12 04:35 UTC, sus-taguchi-t approved these changes

2024-03-25 07:04 UTC, sus-taguchi-t requested changes

2024-03-25 07:04 UTC, sus-taguchi-t commented on docs/integration/web.common.md
> +callback("DoTraceLogSuppressedCallback", "param1", "param2", isSuppressTraceLog = true);
typescript ではこの書き方をするとコンパイルエラーが起きます（キーワード引数を書こうとすると違う書き方になります）。
右側にコメントアウトして「この部分が `isSuppressTraceLog` である」ということを示唆するくらいしかできないと思います。

2024-04-01 06:33 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +関数登録時またはコールバック時に、ログ出力を抑制することができます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/26442feb5d0882af51b996ea8f6cd939446351bf

2024-04-01 06:34 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +import { addAction, addFunction } from "@extreal-dev/extreal.integration.web.common";
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/562f136b030a444f8a37add7466d804445cadbfb

2024-04-01 06:34 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +callback("DoTraceLogSuppressedCallback", "param1", "param2", isSuppressTraceLog = true);
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/ed515e1191a3247e10b0ec60a98880b9c803c274 https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/0803867dc5b4d37a1d4109ff39931aabc546c7cd

2024-04-01 06:50 UTC, sus-taguchi-t commented on docs/integration/web.common.md
> +関数登録時またはコールバック時に、ログ出力を抑制することができます。
There are times when you want to suppress this log output, such as when there are functions or callbacks that are called frequently.
-> Sometimes you may want to suppress this log output, such as when functions or callbacks are called at a high frequency.

2024-04-01 06:50 UTC, sus-taguchi-t commented on docs/integration/web.common.md
> +import { addAction, addFunction } from "@extreal-dev/extreal.integration.web.common";
確認しました。

2024-04-01 06:51 UTC, sus-taguchi-t commented on docs/integration/web.common.md
> +callback("DoTraceLogSuppressedCallback", "param1", "param2", isSuppressTraceLog = true);
確認しました。

2024-04-01 07:10 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +関数登録時またはコールバック時に、ログ出力を抑制することができます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/fa18e72de6322e40e008dab3016f6c5f6d56bdb3

2024-04-01 07:12 UTC, sus-taguchi-t commented on docs/integration/web.common.md
> +関数登録時またはコールバック時に、ログ出力を抑制することができます。
確認しました。

2024-04-01 07:12 UTC, sus-taguchi-t approved these changes

2024-04-04 08:17 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- 指定した関数呼び出しとコールバックのログを抑制する機能を追加しました。([Doc](../integration/web.common.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/7))
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/60/commits/f2e986f050bb9066555ef422e834564e1bb2826a

2024-04-04 08:29 UTC, merged