P2P.WebRTCのWebGLのスティッキーセッション有効化方法のガイド追記
extreal-dev/Extreal.Guide pull request #62
Opened 2024-01-26 06:47 UTC by sus-yoshikane-t

﻿# 何の変更を加えましたか？

- P2P.WebRTCのWebGLでスティッキーセッションを有効にする方法を追記しました。
  - [ライブラリのPR](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/13)

# 何を確認しましたか?

- [x] 変更したページと影響がありそうなページをブラウザで確認しました
- [x] 日本語と英語のページが一致していることを確認しました
- [x] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

ライブラリのPR
- [WebGLのスティッキーセッションへの対応](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/13)

2024-01-29 01:54 UTC, sus-taguchi-t requested changes

2024-01-29 01:54 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +:::
このライブラリを使用したい人はこのリンクを見て何かしなければいけないのでしょうか？

2024-02-21 04:56 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +:::
スティッキーセッションが必要な形の複数サーバーを立てる場合に適切にサーバーの設定を行う、というサーバー側の話のため、削除しました。https://github.com/extreal-dev/Extreal.Guide/pull/62/commits/8bba9197b436ba8a2dccafc2cdd3026b3d56cbe7

2024-02-21 05:36 UTC, kiyohome requested changes

2024-02-21 05:36 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +### スティッキーセッションの有効化
ここの見出しは、Specificationに合わせてます。
Specification
「fシグナリングサーバーを冗長化できます。」
ここの見出し
「シグナリングサーバーを冗長化する」
とかでしょうか。

2024-02-21 05:36 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +
冒頭に入れてください。
シグナリングサーバーには[Socket.IO]を利用しています。Socket.IOサーバーを複数にして冗長化する場合はスティッキーセッションが推奨されています。詳細は[Using multiple nodes]を参照してください。

スティッキーセッションを有効にするにはPeerClientの作成時に・・・ここからは今の文章で大丈夫です。

2024-02-21 05:36 UTC, kiyohome commented on docs/release/unreleased.md
> +- WebGLでスティッキーセッションを使用する設定ができるように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/13))
「シグナリングサーバーを冗長化できるようにスティッキーセッションを有効化する設定を追加しました。」とかでしょうか。

2024-02-21 06:04 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +### スティッキーセッションの有効化
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/62/commits/69e481957df277867fbe833098355253f9a0c36b

2024-02-21 06:04 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +
追記しました。https://github.com/extreal-dev/Extreal.Guide/pull/62/commits/16b53af6617edab40c10d910359fb993879513fd

2024-02-21 06:05 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- WebGLでスティッキーセッションを使用する設定ができるように変更しました。([Doc](../integration/p2p.webrtc.md), [PR](https://github.com/extreal-dev/Extreal.Integration.P2P.WebRTC/pull/13))
修正しました。（追加機能だったためAddedに移動しました。）https://github.com/extreal-dev/Extreal.Guide/pull/62/commits/6c3fa491033a3b2c994f85e0fa2fe283936d729a

2024-02-21 06:09 UTC, kiyohome commented on docs/integration/p2p.webrtc.md
> +
英語の方にはリンクが入ってないです。

2024-02-21 06:15 UTC, sus-yoshikane-t commented on docs/integration/p2p.webrtc.md
> +
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/62/commits/560365bfb5c246819d69ac29b2a1ce69a34e2a5a

2024-02-21 06:17 UTC, kiyohome approved these changes

2024-02-26 01:45 UTC, sus-taguchi-t commented on docs/integration/p2p.webrtc.md
> +:::
確認しました。

2024-02-26 01:47 UTC, sus-taguchi-t approved these changes

2024-02-26 01:47 UTC, merged