WebGLでのビデオ再生をJavaScriptに委譲できるようにする
extreal-dev/Extreal.Guide pull request #64
Opened 2024-02-06 07:54 UTC by sus-taguchi-t

﻿# 何の変更を加えましたか？

- 「WebGLでのビデオ再生をJavaScriptに委譲できるようにする」機能についてガイドを追記しました

# 何を確認しましたか?

- [ ] 変更したページと影響がありそうなページをブラウザで確認しました
- [ ] 日本語と英語のページが一致していることを確認しました
- [ ] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2024-02-20 10:34 UTC, kiyohome requested changes

2024-02-20 10:34 UTC, kiyohome commented on docs/integration/web.common.md
> +### Video
VideoPlayerでしょうか。

2024-02-20 10:34 UTC, kiyohome commented on docs/integration/web.common.md
> +- WebGLでのビデオ再生をJavaScriptに委譲できます。
WebGlでの、と書かれるとWebGL向け機能に勘違いしました。
プラットフォームに応じたビデオ再生ができます。
とかでどうでしょうか。

2024-02-20 10:34 UTC, kiyohome commented on docs/release/unreleased.md
> +- WebGLでのビデオ再生をJavaScriptに委譲する機能を追加しました。([Doc](../integration/web.common.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/9))
specを見直したらこちらも変更をお願いします。

2024-02-22 06:01 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +### Video
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/64/commits/28d66621a4b6d3e9b798b9749ae6d1a0a08ca9f8

2024-02-22 06:01 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +- WebGLでのビデオ再生をJavaScriptに委譲できます。
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/64/commits/8c90fc00e8c3389c717def56aa46d64524b13acb

2024-02-22 06:01 UTC, sus-yoshikane-t commented on docs/release/unreleased.md
> +- WebGLでのビデオ再生をJavaScriptに委譲する機能を追加しました。([Doc](../integration/web.common.md), [PR](https://github.com/extreal-dev/Extreal.Integration.Web.Common/pull/9))
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/64/commits/91425e220a963494352c74259edc876b73031adf

2024-02-22 06:46 UTC, kiyohome requested changes

2024-02-22 06:46 UTC, kiyohome commented on docs/integration/web.common.md
> +#### Video
ここもVideoPlayerでは？

2024-02-22 06:46 UTC, kiyohome commented on docs/integration/web.common.md
> +### WebGLでのビデオ再生をJavaScriptに委譲する
Specificationに合わせて、ここの見出しも変更してください。

2024-02-22 07:48 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +#### Video
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/64/commits/d9f3e1c75bc02bb32b0975f0bd981edc1fc5da0d

2024-02-22 07:48 UTC, sus-yoshikane-t commented on docs/integration/web.common.md
> +### WebGLでのビデオ再生をJavaScriptに委譲する
修正しました。https://github.com/extreal-dev/Extreal.Guide/pull/64/commits/d9f3e1c75bc02bb32b0975f0bd981edc1fc5da0d

2024-02-22 08:57 UTC, kiyohome approved these changes

2024-02-22 08:58 UTC, merged