SFU.OME にリトライを導入
extreal-dev/Extreal.Guide pull request #69
Opened 2024-03-14 06:12 UTC by sus-taguchi-t

﻿# 何の変更を加えましたか？

- SFU.OME にリトライのトリガーについて追記しました
- SFU.OME に join が失敗する可能性がある旨を追記しました

# 何を確認しましたか?

- [x] 変更したページと影響がありそうなページをブラウザで確認しました
- [x] 日本語と英語のページが一致していることを確認しました
    - 英語対応は別の PBI で行う
- [x] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2024-03-15 00:24 UTC, kiyohome requested changes

2024-03-15 00:24 UTC, kiyohome commented on docs/integration/sfu.ome.md
> +このときのタイムアウト時間は30秒で3回までリトライします。
タイムアウト時間と回数は設定で指定できるよにした方がよくないでしょうか？

2024-03-15 00:25 UTC, sus-taguchi-t commented on docs/integration/sfu.ome.md
> +このときのタイムアウト時間は30秒で3回までリトライします。
そう思います。
修正します。

2024-03-26 07:41 UTC, sus-taguchi-t commented on docs/integration/sfu.ome.md
> +このときのタイムアウト時間は30秒で3回までリトライします。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/69/commits/f35cfd890ef6a91104d8b4b7e3feb9adfb14bde0

2024-04-16 00:58 UTC, closed without merging