OME の機能を削除
extreal-dev/Extreal.Guide pull request #72
Opened 2024-04-01 08:51 UTC by sus-taguchi-t

﻿# 何の変更を加えましたか？

- sfu.ome および chat.ome を削除しました
  - integration ディレクトリ以下から削除しました
  - intro.md から削除しました
  - unreleased.md から削除しました
- Holiday のボイスチャットを OME でなく P2P を使用する形に修正しました

# 何を確認しましたか?

- [x] 変更したページと影響がありそうなページをブラウザで確認しました
- [x] 日本語と英語のページが一致していることを確認しました
- [x] リンクや画像のファイルパスは拡張子付きの相対パスになっていることを確認しました
  - [Link docs by file paths](https://docusaurus.io/docs/next/versioning#link-docs-by-file-paths)
  - [Global or versioned collocated assets](https://docusaurus.io/docs/next/versioning#global-or-versioned-collocated-assets)(using per-version)

# レビュアーへのメッセージ

2024-04-02 05:07 UTC, sus-yoshikane-t approved these changes

2024-04-02 06:25 UTC, kiyohome requested changes

2024-04-02 06:25 UTC, kiyohome commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
図中のP2Pへの依存線のコメント「P2P negotiation」のところ、Voice chatにした方がmultiplay/text chatとの違いが分かってよいかと思いました。

2024-04-02 06:25 UTC, kiyohome commented on docs/sample-app/intro.md
> +マルチプレイとテキストチャットは[Messaging](../integration/messaging.md)、ボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
今の書き方だと「グループ選択画面でホストまたはクライアントを選んでグループでプレイします。」が全体に関係しているように感じましたが、マルチプレイとテキストチャットはグループに関係なく全ユーザーに見えますよね？

前半の「マルチプレイ～採用しており、」を削除して「グループ選択画面でホストまたはクライアントを選んでグループで会話しながらプレイできます。」とだけ書いておけばいいかと思いました。
どの機能でMessagingやP2Pを使ってるかはシステム構成を見れば分かるかと思います。

2024-04-02 06:25 UTC, kiyohome commented on docs/sample-app/requirements.md
> +  - ボイスチャット（P2P）
変更箇所でなくコメント付けれなかったので適当な場所にコメントしてます。
Functional requirementsで、マルチプレイ/テキストチャットの範囲はスペース毎、ボイスチャットの範囲はグループ毎であることが明示されてないように感じました。

2024-04-02 06:25 UTC, kiyohome commented on docs/sample-app/requirements.md
> +  - ボイスチャット（P2P）
変更箇所でなくコメント付けれなかったので適当な場所にコメントしてます。
非機能のところに下記の記載があります。

- 利用人数
  - マルチプレイ
    - 1スペース70人
  - テキスト/ボイスチャット
    - 1グループ10人

テキストチャットはMessaging使ってスペース内で全員に見えると思ってましたが違いますか？

2024-04-02 06:32 UTC, sus-taguchi-t commented on docs/sample-app/intro.md
> +マルチプレイとテキストチャットは[Messaging](../integration/messaging.md)、ボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
確かにその通りですね。
ただマルチプレイのみ全ユーザに見えてテキストチャットとボイスチャットはグループで行うという仕様なのですが、それでも「グループ選択画面でホストまたはクライアントを選んでグループで会話しながらプレイできます。」という文で伝わるのでそのように対応します。

2024-04-02 06:35 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - ボイスチャット（P2P）
修正します。
現在の仕様は以下です。
- スペースごと
  - マルチプレイ
- グループごと
  - テキストチャット
  - ボイスチャット

2024-04-02 06:36 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - ボイスチャット（P2P）
はい、違います。
現在の仕様としては前のコメントの通りです。
https://github.com/extreal-dev/Extreal.Guide/pull/72#discussion_r1547213374

2024-04-02 06:38 UTC, sus-taguchi-t commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
「Voice chat」というコメントが 2 つになるのは違和感があるので「P2P negotiation (voice chat)」としようと思いますがいかがでしょうか？

2024-04-03 08:51 UTC, sus-taguchi-t commented on docs/sample-app/intro.md
> +マルチプレイとテキストチャットは[Messaging](../integration/messaging.md)、ボイスチャットはP2P(Peer to Peer)を採用しており、グループ選択画面でホストまたはクライアントを選んでグループでプレイします。
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/72/commits/b0908b7ced534667510711dcbb4a1d57402c1298

2024-04-03 08:51 UTC, sus-taguchi-t commented on docs/sample-app/architecture.md
>  ![system structure](../img/holiday-sys-structure.png)
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/72/commits/de0f25e82cc4863b449b4939419f0bb861ec3760

2024-04-03 08:52 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - ボイスチャット（P2P）
以下の仕様で合意したので改めてこちらに合わせて修正します。
- スペースごと
  - マルチプレイ
  - テキストチャット
- グループごと
  - ボイスチャット

2024-04-03 08:55 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - ボイスチャット（P2P）
修正しました。
他も横並びチェックしてテスト計画とアプリ構成図も修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/72/commits/b27388ead3f03d2fe43dd02cd2fccbce5afe6089

2024-04-03 08:55 UTC, sus-taguchi-t commented on docs/sample-app/requirements.md
> +  - ボイスチャット（P2P）
前の[指摘](https://github.com/extreal-dev/Extreal.Guide/pull/72#discussion_r1549278705)に合わせて修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/72/commits/b27388ead3f03d2fe43dd02cd2fccbce5afe6089

2024-04-03 08:57 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
マルチプレイなどの実現方法について記述してみましたのでご確認お願いします。

2024-04-03 09:22 UTC, kiyohome approved these changes

2024-04-03 09:22 UTC, kiyohome commented on docs/sample-app/dev-guide.md
他の開発メンバーにもピアレビューしてもらってください。

2024-04-04 01:45 UTC, kiyohome approved these changes

2024-04-04 06:13 UTC, sus-yoshikane-t requested changes

2024-04-04 06:20 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +              .AddTo(sceneDisposables);
すみません、ありがとうございます。
修正します。

2024-04-04 06:23 UTC, sus-taguchi-t commented on docs/sample-app/dev-guide.md
> +              .AddTo(sceneDisposables);
修正しました。
https://github.com/extreal-dev/Extreal.Guide/pull/72/commits/617d8dd33eac62e02b49b9bd415201debce78a5e

2024-04-04 06:40 UTC, sus-yoshikane-t commented on docs/sample-app/dev-guide.md
> +              .AddTo(sceneDisposables);
確認しました。

2024-04-04 06:40 UTC, sus-yoshikane-t approved these changes

2024-04-04 06:53 UTC, merged